from typing import Tuple, Set, Iterable, List


class Section:
    def __init__(self): ...
    @property
    def DebugMode(self) -> Nullable: ...
    @property
    def PrivateBinding(self) -> Nullable: ...
    def GetLanguages(self) -> Iterable[LanguageElement]: ...
    def GetOptions(self) -> Iterable[OptionElement]: ...
    @DebugMode.setter
    def DebugMode(self, value: Nullable) -> None: ...
    @PrivateBinding.setter
    def PrivateBinding(self, value: Nullable) -> None: ...
