from typing import Tuple, Set, Iterable, List


class Extensions(Object):
    @overload
    def GetSchemaInfo(source: XElement) -> IXmlSchemaInfo: ...
    @overload
    def GetSchemaInfo(source: XAttribute) -> IXmlSchemaInfo: ...
    @overload
    def Validate(source: XDocument, schemas: XmlSchemaSet, validationEventHandler: ValidationEventHandler) -> None: ...
    @overload
    def Validate(source: XDocument, schemas: XmlSchemaSet, validationEventHandler: ValidationEventHandler, addSchemaInfo: bool) -> None: ...
    @overload
    def Validate(source: XElement, partialValidationType: XmlSchemaObject, schemas: XmlSchemaSet, validationEventHandler: ValidationEventHandler) -> None: ...
    @overload
    def Validate(source: XAttribute, partialValidationType: XmlSchemaObject, schemas: XmlSchemaSet, validationEventHandler: ValidationEventHandler) -> None: ...
    @overload
    def Validate(source: XElement, partialValidationType: XmlSchemaObject, schemas: XmlSchemaSet, validationEventHandler: ValidationEventHandler, addSchemaInfo: bool) -> None: ...
    @overload
    def Validate(source: XAttribute, partialValidationType: XmlSchemaObject, schemas: XmlSchemaSet, validationEventHandler: ValidationEventHandler, addSchemaInfo: bool) -> None: ...
