from typing import Tuple, Set, Iterable, List


class MemoryCacheSettingsCollection(ConfigurationElementCollection):
    def __init__(self): ...
    def Add(self, cache: MemoryCacheElement) -> None: ...
    def Clear(self) -> None: ...
    @property
    def CollectionType(self) -> ConfigurationElementCollectionType: ...
    @property
    def Item(self, index: int) -> MemoryCacheElement: ...
    @property
    def Item(self, key: str) -> MemoryCacheElement: ...
    def IndexOf(self, cache: MemoryCacheElement) -> int: ...
    def Remove(self, cache: MemoryCacheElement) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    @Item.setter
    def Item(self, index: int, value: MemoryCacheElement) -> None: ...
