from typing import Tuple, Set, Iterable, List


class LugsGPOSettings(PolicyMakerElement):
    def __init__(self): ...
    @property
    def LugsSettingsList(self) -> Collection: ...
    @LugsSettingsList.setter
    def LugsSettingsList(self, value: Collection) -> None: ...
