from typing import Tuple, Set, Iterable, List


class LocalGroupGPOSetting(LugsGPOSettingBase):
    def __init__(self): ...
    def GetHashKey(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...


class LocalGroupMember:
    def __init__(self): ...
    @property
    def Action(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Sid(self) -> str: ...
    @Action.setter
    def Action(self, value: str) -> None: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @Sid.setter
    def Sid(self, value: str) -> None: ...


class LocalGroupProperties(PolicyMakerProperties):
    def __init__(self): ...
    @property
    def Members(self) -> Collection: ...
    @Members.setter
    def Members(self, value: Collection) -> None: ...


class LocalUserGPOSetting(LugsGPOSettingBase):
    def __init__(self): ...
    def GetHashKey(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...


class LugsGPOSettingBase:
    def GetHashKey(self) -> str: ...


class LugsGPOSettings(PolicyMakerElement):
    def __init__(self): ...
    @property
    def LugsSettingsList(self) -> Collection: ...
    @LugsSettingsList.setter
    def LugsSettingsList(self, value: Collection) -> None: ...


class LugsRsopSetting(PolicyMakerRsopSetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, managementObject: ManagementObject): ...
    def GetHashKey(self) -> str: ...
    def GetItemSubInstanceAttributeName(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...


class LugsSettings(PolicyMakerSettings):
    def __init__(self): ...
    @property
    def LugsGPOSettings(self) -> LugsGPOSettings: ...
    @property
    def LugsRsopSettings(self) -> Collection: ...
    def GetGPOSettings(self) -> ICollection: ...
    def GetRsopSettings(self) -> ICollection: ...
    def Initialize(self, context: ReportingContext) -> None: ...
    @LugsGPOSettings.setter
    def LugsGPOSettings(self, value: LugsGPOSettings) -> None: ...
    @LugsRsopSettings.setter
    def LugsRsopSettings(self, value: Collection) -> None: ...
