__all__ = ['Internal']
from typing import Tuple, Set, Iterable, List


class HelpWindow:
    def __init__(self, helpObject: PSObject): ...
    def InitializeComponent(self) -> None: ...


class SettingsDialog:
    def __init__(self): ...
    def InitializeComponent(self) -> None: ...
