__all__ = ['Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema']
from typing import Tuple, Set, Iterable, List


class XamlXmlWriterSettings(XamlWriterSettings):
    def __init__(self): ...
    def Copy(self) -> XamlXmlWriterSettings: ...
    @property
    def AssumeValidInput(self) -> bool: ...
    @property
    def CloseOutput(self) -> bool: ...
    @AssumeValidInput.setter
    def AssumeValidInput(self, value: bool) -> None: ...
    @CloseOutput.setter
    def CloseOutput(self, value: bool) -> None: ...
