from typing import Tuple, Set, Iterable, List


class UrlPrefixCollection:
    @overload
    def Add(self, prefix: str) -> None: ...
    @overload
    def Add(self, item: UrlPrefix) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, item: UrlPrefix) -> bool: ...
    def CopyTo(self, array: Set(UrlPrefix), arrayIndex: int) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def IsReadOnly(self) -> bool: ...
    def GetEnumerator(self) -> IEnumerator: ...
    @overload
    def Remove(self, prefix: str) -> bool: ...
    @overload
    def Remove(self, item: UrlPrefix) -> bool: ...
