from typing import Tuple, Set, Iterable, List


class HttpRemotingHandlerFactory(Object):
    def __init__(self): ...
    def GetHandler(self, context: HttpContext, verb: str, url: str, filePath: str) -> IHttpHandler: ...
    def ReleaseHandler(self, handler: IHttpHandler) -> None: ...
