from typing import Tuple, Set, Iterable, List


class ProjectionSourceSpansChangedEventArgs(TextContentChangedEventArgs):
    def __init__(self, beforeSnapshot: IProjectionSnapshot, afterSnapshot: IProjectionSnapshot, insertedSpans: List[ITrackingSpan], deletedSpans: List[ITrackingSpan], spanPosition: int, options: EditOptions, editTag: Object): ...
    @property
    def After(self) -> IProjectionSnapshot: ...
    @property
    def Before(self) -> IProjectionSnapshot: ...
    @property
    def DeletedSpans(self) -> ReadOnlyCollection: ...
    @property
    def InsertedSpans(self) -> ReadOnlyCollection: ...
    @property
    def SpanPosition(self) -> int: ...
