from typing import Tuple, Set, Iterable, List


class UdpTransportSettingsElement(ConfigurationElement):
    def __init__(self): ...
    @property
    def DuplicateMessageHistoryLength(self) -> int: ...
    @property
    def MaxBufferPoolSize(self) -> Int64: ...
    @property
    def MaxMulticastRetransmitCount(self) -> int: ...
    @property
    def MaxPendingMessageCount(self) -> int: ...
    @property
    def MaxReceivedMessageSize(self) -> Int64: ...
    @property
    def MaxUnicastRetransmitCount(self) -> int: ...
    @property
    def MulticastInterfaceId(self) -> str: ...
    @property
    def SocketReceiveBufferSize(self) -> int: ...
    @property
    def TimeToLive(self) -> int: ...
    @DuplicateMessageHistoryLength.setter
    def DuplicateMessageHistoryLength(self, value: int) -> None: ...
    @MaxBufferPoolSize.setter
    def MaxBufferPoolSize(self, value: Int64) -> None: ...
    @MaxMulticastRetransmitCount.setter
    def MaxMulticastRetransmitCount(self, value: int) -> None: ...
    @MaxPendingMessageCount.setter
    def MaxPendingMessageCount(self, value: int) -> None: ...
    @MaxReceivedMessageSize.setter
    def MaxReceivedMessageSize(self, value: Int64) -> None: ...
    @MaxUnicastRetransmitCount.setter
    def MaxUnicastRetransmitCount(self, value: int) -> None: ...
    @MulticastInterfaceId.setter
    def MulticastInterfaceId(self, value: str) -> None: ...
    @SocketReceiveBufferSize.setter
    def SocketReceiveBufferSize(self, value: int) -> None: ...
    @TimeToLive.setter
    def TimeToLive(self, value: int) -> None: ...
