from typing import Tuple, Set, Iterable, List


class AnnouncementChannelEndpointElementCollection:
    def __init__(self): ...


class AnnouncementEndpointCollectionElement:
    def __init__(self): ...


class AnnouncementEndpointElement(StandardEndpointElement):
    def __init__(self): ...
    @property
    def DiscoveryVersion(self) -> DiscoveryVersion: ...
    @property
    def MaxAnnouncementDelay(self) -> TimeSpan: ...
    @DiscoveryVersion.setter
    def DiscoveryVersion(self, value: DiscoveryVersion) -> None: ...
    @MaxAnnouncementDelay.setter
    def MaxAnnouncementDelay(self, value: TimeSpan) -> None: ...


class ContractTypeNameElement(ConfigurationElement):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, name: str, ns: str): ...
    @property
    def Name(self) -> str: ...
    @property
    def Namespace(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @Namespace.setter
    def Namespace(self, value: str) -> None: ...


class ContractTypeNameElementCollection:
    def __init__(self): ...


class DiscoveryClientElement(BindingElementExtensionElement):
    def __init__(self): ...
    def ApplyConfiguration(self, bindingElement: BindingElement) -> None: ...
    def CopyFrom(self, from_: ServiceModelExtensionElement) -> None: ...
    @property
    def BindingElementType(self) -> Type: ...
    @property
    def DiscoveryEndpoint(self) -> ChannelEndpointElement: ...
    @property
    def FindCriteria(self) -> FindCriteriaElement: ...


class DiscoveryClientSettingsElement(ConfigurationElement):
    def __init__(self): ...
    @property
    def DiscoveryEndpoint(self) -> ChannelEndpointElement: ...
    @property
    def FindCriteria(self) -> FindCriteriaElement: ...


class DiscoveryEndpointCollectionElement:
    def __init__(self): ...


class DiscoveryEndpointElement(StandardEndpointElement):
    def __init__(self): ...
    @property
    def DiscoveryMode(self) -> ServiceDiscoveryMode: ...
    @property
    def DiscoveryVersion(self) -> DiscoveryVersion: ...
    @property
    def MaxResponseDelay(self) -> TimeSpan: ...
    @DiscoveryMode.setter
    def DiscoveryMode(self, value: ServiceDiscoveryMode) -> None: ...
    @DiscoveryVersion.setter
    def DiscoveryVersion(self, value: DiscoveryVersion) -> None: ...
    @MaxResponseDelay.setter
    def MaxResponseDelay(self, value: TimeSpan) -> None: ...


class DiscoveryVersionConverter(TypeConverter):
    def __init__(self): ...
    @overload
    def CanConvertFrom(self, context: ITypeDescriptorContext, sourceType: Type) -> bool: ...
    @overload
    def CanConvertTo(self, context: ITypeDescriptorContext, destinationType: Type) -> bool: ...
    @overload
    def ConvertFrom(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object) -> Object: ...
    @overload
    def ConvertTo(self, context: ITypeDescriptorContext, culture: CultureInfo, value: Object, destinationType: Type) -> Object: ...


class DynamicEndpointCollectionElement:
    def __init__(self): ...


class DynamicEndpointElement(StandardEndpointElement):
    def __init__(self): ...
    @property
    def DiscoveryClientSettings(self) -> DiscoveryClientSettingsElement: ...


class EndpointDiscoveryElement(BehaviorExtensionElement):
    def __init__(self): ...
    @property
    def BehaviorType(self) -> Type: ...
    @property
    def ContractTypeNames(self) -> ContractTypeNameElementCollection: ...
    @property
    def Enabled(self) -> bool: ...
    @property
    def Extensions(self) -> XmlElementElementCollection: ...
    @property
    def Scopes(self) -> ScopeElementCollection: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> None: ...


class FindCriteriaElement(ConfigurationElement):
    def __init__(self): ...
    @property
    def ContractTypeNames(self) -> ContractTypeNameElementCollection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @property
    def Extensions(self) -> XmlElementElementCollection: ...
    @property
    def MaxResults(self) -> int: ...
    @property
    def ScopeMatchBy(self) -> Uri: ...
    @property
    def Scopes(self) -> ScopeElementCollection: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> None: ...
    @MaxResults.setter
    def MaxResults(self, value: int) -> None: ...
    @ScopeMatchBy.setter
    def ScopeMatchBy(self, value: Uri) -> None: ...


class ScopeElement(ConfigurationElement):
    def __init__(self): ...
    @property
    def Scope(self) -> Uri: ...
    @Scope.setter
    def Scope(self, value: Uri) -> None: ...


class ScopeElementCollection:
    def __init__(self): ...


class ServiceDiscoveryElement(BehaviorExtensionElement):
    def __init__(self): ...
    @property
    def AnnouncementEndpoints(self) -> AnnouncementChannelEndpointElementCollection: ...
    @property
    def BehaviorType(self) -> Type: ...


class UdpAnnouncementEndpointCollectionElement:
    def __init__(self): ...


class UdpAnnouncementEndpointElement(AnnouncementEndpointElement):
    def __init__(self): ...
    @property
    def MaxAnnouncementDelay(self) -> TimeSpan: ...
    @property
    def MulticastAddress(self) -> Uri: ...
    @property
    def TransportSettings(self) -> UdpTransportSettingsElement: ...
    @MaxAnnouncementDelay.setter
    def MaxAnnouncementDelay(self, value: TimeSpan) -> None: ...
    @MulticastAddress.setter
    def MulticastAddress(self, value: Uri) -> None: ...


class UdpDiscoveryEndpointCollectionElement:
    def __init__(self): ...


class UdpDiscoveryEndpointElement(DiscoveryEndpointElement):
    def __init__(self): ...
    @property
    def DiscoveryMode(self) -> ServiceDiscoveryMode: ...
    @property
    def MaxResponseDelay(self) -> TimeSpan: ...
    @property
    def MulticastAddress(self) -> Uri: ...
    @property
    def TransportSettings(self) -> UdpTransportSettingsElement: ...
    @DiscoveryMode.setter
    def DiscoveryMode(self, value: ServiceDiscoveryMode) -> None: ...
    @MaxResponseDelay.setter
    def MaxResponseDelay(self, value: TimeSpan) -> None: ...
    @MulticastAddress.setter
    def MulticastAddress(self, value: Uri) -> None: ...


class UdpTransportSettingsElement(ConfigurationElement):
    def __init__(self): ...
    @property
    def DuplicateMessageHistoryLength(self) -> int: ...
    @property
    def MaxBufferPoolSize(self) -> Int64: ...
    @property
    def MaxMulticastRetransmitCount(self) -> int: ...
    @property
    def MaxPendingMessageCount(self) -> int: ...
    @property
    def MaxReceivedMessageSize(self) -> Int64: ...
    @property
    def MaxUnicastRetransmitCount(self) -> int: ...
    @property
    def MulticastInterfaceId(self) -> str: ...
    @property
    def SocketReceiveBufferSize(self) -> int: ...
    @property
    def TimeToLive(self) -> int: ...
    @DuplicateMessageHistoryLength.setter
    def DuplicateMessageHistoryLength(self, value: int) -> None: ...
    @MaxBufferPoolSize.setter
    def MaxBufferPoolSize(self, value: Int64) -> None: ...
    @MaxMulticastRetransmitCount.setter
    def MaxMulticastRetransmitCount(self, value: int) -> None: ...
    @MaxPendingMessageCount.setter
    def MaxPendingMessageCount(self, value: int) -> None: ...
    @MaxReceivedMessageSize.setter
    def MaxReceivedMessageSize(self, value: Int64) -> None: ...
    @MaxUnicastRetransmitCount.setter
    def MaxUnicastRetransmitCount(self, value: int) -> None: ...
    @MulticastInterfaceId.setter
    def MulticastInterfaceId(self, value: str) -> None: ...
    @SocketReceiveBufferSize.setter
    def SocketReceiveBufferSize(self, value: int) -> None: ...
    @TimeToLive.setter
    def TimeToLive(self, value: int) -> None: ...
