from typing import Tuple, Set, Iterable, List


class WarningHeaderValue(Object):
    @overload
    def __init__(self, code: int, agent: str, text: str): ...
    @overload
    def __init__(self, code: int, agent: str, text: str, date: DateTimeOffset): ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def Agent(self) -> str: ...
    @property
    def Code(self) -> int: ...
    @property
    def Date(self) -> Nullable: ...
    @property
    def Text(self) -> str: ...
    def GetHashCode(self) -> int: ...
    def Parse(input: str) -> WarningHeaderValue: ...
    def ToString(self) -> str: ...
    def TryParse(input: str) -> Tuple[bool, WarningHeaderValue]: ...
