from typing import Tuple, Set, Iterable, List


class ChunkingCookieManager:
    def __init__(self): ...
    def AppendResponseCookie(self, context: HttpContext, key: str, value: str, options: CookieOptions) -> None: ...
    def DeleteCookie(self, context: HttpContext, key: str, options: CookieOptions) -> None: ...
    @property
    def ChunkSize(self) -> Nullable: ...
    @property
    def ThrowForPartialCookies(self) -> bool: ...
    def GetRequestCookie(self, context: HttpContext, key: str) -> str: ...
    @ChunkSize.setter
    def ChunkSize(self, value: Nullable) -> None: ...
    @ThrowForPartialCookies.setter
    def ThrowForPartialCookies(self, value: bool) -> None: ...
