from typing import Tuple, Set, Iterable, List


class AppvClientApplication:
    def EnumerateApplications() -> Iterable[AppvClientApplication]: ...
    @property
    def ApplicationId(self) -> str: ...
    @property
    def EnabledForUser(self) -> bool: ...
    @property
    def EnabledGlobally(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def PackageId(self) -> str: ...
    @property
    def PackageVersionId(self) -> str: ...
    @property
    def TargetPath(self) -> str: ...
    @property
    def Version(self) -> str: ...
    def GetInstance(packageId: str, packageVersionId: str, applicationId: str) -> AppvClientApplication: ...


class AppvClientAsset:
    def Enumerate() -> Iterable[AppvClientAsset]: ...
    @property
    def ChannelCode(self) -> str: ...
    @property
    def CM_DSLID(self) -> str: ...
    @property
    def InstallDate(self) -> str: ...
    @property
    def InstalledLocation(self) -> str: ...
    @property
    def Language(self) -> str: ...
    @property
    def OsComponent(self) -> str: ...
    @property
    def PackageId(self) -> str: ...
    @property
    def PackageVersionId(self) -> str: ...
    @property
    def ProductID(self) -> str: ...
    @property
    def ProductName(self) -> str: ...
    @property
    def ProductVersion(self) -> str: ...
    @property
    def Publisher(self) -> str: ...
    @property
    def RegisteredUser(self) -> str: ...
    @property
    def ServicePack(self) -> str: ...
    @property
    def SoftwareCode(self) -> str: ...
    @property
    def UpgradeCode(self) -> str: ...
    @property
    def VersionMajor(self) -> str: ...
    @property
    def VersionMinor(self) -> str: ...
    def GetInstance(packageId: str, packageVersionId: str, softwareCode: str) -> AppvClientAsset: ...
    def ToString(self) -> str: ...


class AppvClientConnectionGroup:
    def EnumerateGroups() -> Iterable[AppvClientConnectionGroup]: ...
    @property
    def CustomData(self) -> str: ...
    @property
    def GlobalPending(self) -> bool: ...
    @property
    def GroupId(self) -> str: ...
    @property
    def InUse(self) -> bool: ...
    @property
    def IsEnabledGlobally(self) -> bool: ...
    @property
    def IsEnabledToUser(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Packages(self) -> Set(str): ...
    @property
    def PercentLoaded(self) -> UInt16: ...
    @property
    def Priority(self) -> UInt32: ...
    @property
    def UserPending(self) -> bool: ...
    @property
    def VersionId(self) -> str: ...
    def GetInstance(groupIdStr: str, versionIdStr: str) -> AppvClientConnectionGroup: ...


class AppvClientPackage:
    def EnumeratePackages() -> Iterable[AppvClientPackage]: ...
    @property
    def Assets(self) -> Set(str): ...
    @property
    def DeploymentMachineData(self) -> str: ...
    @property
    def DeploymentUserData(self) -> str: ...
    @property
    def GlobalPending(self) -> bool: ...
    @property
    def HasAssetIntelligence(self) -> bool: ...
    @property
    def InUse(self) -> bool: ...
    @property
    def IsPublishedGlobally(self) -> bool: ...
    @property
    def IsPublishedToUser(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def PackageId(self) -> str: ...
    @property
    def PackageSize(self) -> UInt64: ...
    @property
    def Path(self) -> str: ...
    @property
    def PercentLoaded(self) -> UInt16: ...
    @property
    def UserConfigurationData(self) -> str: ...
    @property
    def UserPending(self) -> bool: ...
    @property
    def Version(self) -> str: ...
    @property
    def VersionId(self) -> str: ...
    def GetInstance(idStr: str, versionIdStr: str) -> AppvClientPackage: ...
    def ToString(self) -> str: ...
