from typing import Tuple, Set, Iterable, List


class WorkflowViewState(Object):
    def GetIdRef(instance: Object) -> str: ...
    def GetViewStateManager(instance: Object) -> ViewStateManager: ...
    def SetIdRef(instance: Object, idRef: str) -> None: ...
    def SetViewStateManager(instance: Object, viewStateManager: ViewStateManager) -> None: ...
