__all__ = ['Diagnostics','Diagnostics','Diagnostics','Diagnostics','Diagnostics','Diagnostics','Diagnostics','Diagnostics','ModelBinding','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','Rendering','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewComponents','ViewEngines','ViewEngines','ViewEngines','ViewEngines','ViewEngines','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures','ViewFeatures']
from typing import Tuple, Set, Iterable, List


class ViewResult(ActionResult):
    def __init__(self): ...
    def ExecuteResultAsync(self, context: ActionContext) -> Task: ...
    @property
    def ContentType(self) -> str: ...
    @property
    def Model(self) -> Object: ...
    @property
    def StatusCode(self) -> Nullable: ...
    @property
    def TempData(self) -> ITempDataDictionary: ...
    @property
    def ViewData(self) -> ViewDataDictionary: ...
    @property
    def ViewEngine(self) -> IViewEngine: ...
    @property
    def ViewName(self) -> str: ...
    @ContentType.setter
    def ContentType(self, value: str) -> None: ...
    @StatusCode.setter
    def StatusCode(self, value: Nullable) -> None: ...
    @TempData.setter
    def TempData(self, value: ITempDataDictionary) -> None: ...
    @ViewData.setter
    def ViewData(self, value: ViewDataDictionary) -> None: ...
    @ViewEngine.setter
    def ViewEngine(self, value: IViewEngine) -> None: ...
    @ViewName.setter
    def ViewName(self, value: str) -> None: ...
