from typing import Tuple, Set, Iterable, List


class ResponseCachingOptions:
    def __init__(self): ...
    @property
    def MaximumBodySize(self) -> Int64: ...
    @property
    def SizeLimit(self) -> Int64: ...
    @property
    def UseCaseSensitivePaths(self) -> bool: ...
    @MaximumBodySize.setter
    def MaximumBodySize(self, value: Int64) -> None: ...
    @SizeLimit.setter
    def SizeLimit(self, value: Int64) -> None: ...
    @UseCaseSensitivePaths.setter
    def UseCaseSensitivePaths(self, value: bool) -> None: ...
