__all__ = ['SymbolStore','SymbolStore','SymbolStore','SymbolStore','SymbolStore','SymbolStore','SymbolStore','SymbolStore','SymbolStore','SymbolStore','SymbolStore','SymbolStore','SymbolStore','SymbolStore']
from typing import Tuple, Set, Iterable, List


class StackFrameExtensions(Object):
    def GetNativeImageBase(stackFrame: StackFrame) -> IntPtr: ...
    def GetNativeIP(stackFrame: StackFrame) -> IntPtr: ...
    def HasILOffset(stackFrame: StackFrame) -> bool: ...
    def HasMethod(stackFrame: StackFrame) -> bool: ...
    def HasNativeImage(stackFrame: StackFrame) -> bool: ...
    def HasSource(stackFrame: StackFrame) -> bool: ...
