from typing import Tuple, Set, Iterable, List


class HostingHelpers:
    def CreateDocumentationOperations(provider: DocumentationProvider) -> DocumentationOperations: ...
    def CreateScriptScope(engine: ScriptEngine, scope: Scope) -> ScriptScope: ...
    def GetDomainManager(runtime: ScriptRuntime) -> ScriptDomainManager: ...
    def GetLanguageContext(engine: ScriptEngine) -> LanguageContext: ...
    def GetScope(scriptScope: ScriptScope) -> Scope: ...
    def GetScriptCode(compiledCode: CompiledCode) -> ScriptCode: ...
    def GetSharedIO(io: ScriptIO) -> SharedIO: ...
    def GetSourceUnit(scriptSource: ScriptSource) -> SourceUnit: ...
