from typing import Tuple, Set, Iterable, List


class CimSerializer:
    @overload
    def Create() -> CimSerializer: ...
    @overload
    def Create(format: str, flags: UInt32) -> CimSerializer: ...
    def Dispose(self) -> None: ...
    @overload
    def Serialize(self, cimInstance: CimInstance, options: InstanceSerializationOptions) -> Set(Byte): ...
    @overload
    def Serialize(self, cimClass: CimClass, options: ClassSerializationOptions) -> Set(Byte): ...
    @overload
    def Serialize(self, cimInstance: CimInstance, options: InstanceSerializationOptions, buffer: Set(Byte), offset: UInt32) -> Tuple[bool, UInt32]: ...
    @overload
    def Serialize(self, cimClass: CimClass, options: ClassSerializationOptions, buffer: Set(Byte), offset: UInt32) -> Tuple[bool, UInt32]: ...
