from typing import Tuple, Set, Iterable, List


class FilesGPOSetting:
    def __init__(self): ...
    def GetHashKey(self) -> str: ...


class FilesGPOSettings(PolicyMakerElement):
    def __init__(self): ...
    @property
    def Files(self) -> List: ...
    @Files.setter
    def Files(self, value: List) -> None: ...


class FilesRsopSetting(PolicyMakerRsopSetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, managementObject: ManagementObject): ...
    def GetHashKey(self) -> str: ...
    def GetItemSubInstanceAttributeName(self) -> str: ...


class FilesSettings(PolicyMakerSettings):
    def __init__(self): ...
    @property
    def FilesGPOSettings(self) -> FilesGPOSettings: ...
    @property
    def FilesRsopSettings(self) -> List: ...
    def GetGPOSettings(self) -> ICollection: ...
    def GetRsopSettings(self) -> ICollection: ...
    def Initialize(self, context: ReportingContext) -> None: ...
    @FilesGPOSettings.setter
    def FilesGPOSettings(self, value: FilesGPOSettings) -> None: ...
    @FilesRsopSettings.setter
    def FilesRsopSettings(self, value: List) -> None: ...
