from typing import Tuple, Set, Iterable, List


class EmbeddedResourceFileInfo:
    def __init__(self, assembly: Assembly, resourcePath: str, name: str, lastModified: DateTimeOffset): ...
    def CreateReadStream(self) -> Stream: ...
    @property
    def Exists(self) -> bool: ...
    @property
    def IsDirectory(self) -> bool: ...
    @property
    def LastModified(self) -> DateTimeOffset: ...
    @property
    def Length(self) -> Int64: ...
    @property
    def Name(self) -> str: ...
    @property
    def PhysicalPath(self) -> str: ...
