from typing import Tuple, Set, Iterable, List


class LanProfileMsmSecurity:
    def __init__(self): ...
    @property
    def Any(self) -> Set(XmlElement): ...
    @property
    def OneX(self) -> OneX: ...
    @property
    def OneXEnabled(self) -> bool: ...
    @property
    def OneXEnforced(self) -> bool: ...
    @Any.setter
    def Any(self, value: Set(XmlElement)) -> None: ...
    @OneX.setter
    def OneX(self, value: OneX) -> None: ...
    @OneXEnabled.setter
    def OneXEnabled(self, value: bool) -> None: ...
    @OneXEnforced.setter
    def OneXEnforced(self, value: bool) -> None: ...
