from typing import Tuple, Set, Iterable, List


class Size:
    def __init__(self, width: float, height: float): ...
    @overload
    def Equals(self, o: Object) -> bool: ...
    @overload
    def Equals(self, value: Size) -> bool: ...
    @property
    def Empty() -> Size: ...
    @property
    def Height(self) -> float: ...
    @property
    def IsEmpty(self) -> bool: ...
    @property
    def Width(self) -> float: ...
    def GetHashCode(self) -> int: ...
    def op_Equality(size1: Size, size2: Size) -> bool: ...
    def op_Inequality(size1: Size, size2: Size) -> bool: ...
    @Height.setter
    def Height(self, value: float) -> None: ...
    @Width.setter
    def Width(self, value: float) -> None: ...
    def ToString(self) -> str: ...
