from typing import Tuple, Set, Iterable, List


class ValidationSummary(ComponentBase):
    def __init__(self): ...
    @property
    def AdditionalAttributes(self) -> IReadOnlyDictionary: ...
    @property
    def Model(self) -> Object: ...
    @AdditionalAttributes.setter
    def AdditionalAttributes(self, value: IReadOnlyDictionary) -> None: ...
    @Model.setter
    def Model(self, value: Object) -> None: ...
