__all__ = ['Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design','Design']
from typing import Tuple, Set, Iterable, List


class StandardValuesCollection(Object):
    def __init__(self, values: ICollection): ...
    def CopyTo(self, array: Array, index: int) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def Item(self, index: int) -> Object: ...
    def GetEnumerator(self) -> IEnumerator: ...
