from typing import Tuple, Set, Iterable, List


class IHTMLInputElement:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> str: ...
    @name.setter
    def name(self, p: str) -> None: ...
    @value.setter
    def value(self, p: str) -> None: ...
