from typing import Tuple, Set, Iterable, List


class JavaScriptConverter(Object):
    def Deserialize(self, dictionary: IDictionary, type: Type, serializer: JavaScriptSerializer) -> Object: ...
    @property
    def SupportedTypes(self) -> Iterable[Type]: ...
    def Serialize(self, obj: Object, serializer: JavaScriptSerializer) -> IDictionary: ...
