__all__ = ['Virtualization','Virtualization','Virtualization','Virtualization','Virtualization']
from typing import Tuple, Set, Iterable, List


class WheelEventArgs(MouseEventArgs):
    def __init__(self): ...
    @property
    def DeltaMode(self) -> Int64: ...
    @property
    def DeltaX(self) -> float: ...
    @property
    def DeltaY(self) -> float: ...
    @property
    def DeltaZ(self) -> float: ...
    @DeltaMode.setter
    def DeltaMode(self, value: Int64) -> None: ...
    @DeltaX.setter
    def DeltaX(self, value: float) -> None: ...
    @DeltaY.setter
    def DeltaY(self, value: float) -> None: ...
    @DeltaZ.setter
    def DeltaZ(self, value: float) -> None: ...
