from typing import Tuple, Set, Iterable, List


class UnixDomainSocketEndPoint(EndPoint):
    def __init__(self, path: str): ...
    def Create(self, socketAddress: SocketAddress) -> EndPoint: ...
    @property
    def AddressFamily(self) -> AddressFamily: ...
    def Serialize(self) -> SocketAddress: ...
    def ToString(self) -> str: ...
