from typing import Tuple, Set, Iterable, List


class MemoryMappedViewStream(UnmanagedMemoryStream):
    def Flush(self) -> None: ...
    @property
    def PointerOffset(self) -> Int64: ...
    @property
    def SafeMemoryMappedViewHandle(self) -> SafeMemoryMappedViewHandle: ...
    def SetLength(self, value: Int64) -> None: ...
