from typing import Tuple, Set, Iterable, List


class Environment:
    def __init__(self): ...
    def GetWindowsDirectory() -> str: ...


class JsonSerializer:
    def __init__(self): ...
    def Deserialize(serializedObject: str) -> T: ...
    def Serialize(o: Object) -> str: ...
