from typing import Tuple, Set, Iterable, List


class ShowCommandParameterType:
    @overload
    def __init__(self, other: Type): ...
    @overload
    def __init__(self, other: PSObject): ...
    @property
    def ElementType(self) -> ShowCommandParameterType: ...
    @property
    def EnumValues(self) -> ArrayList: ...
    @property
    def FullName(self) -> str: ...
    @property
    def HasFlagAttribute(self) -> bool: ...
    @property
    def ImplementsDictionary(self) -> bool: ...
    @property
    def IsArray(self) -> bool: ...
    @property
    def IsBoolean(self) -> bool: ...
    @property
    def IsEnum(self) -> bool: ...
    @property
    def IsScriptBlock(self) -> bool: ...
    @property
    def IsString(self) -> bool: ...
    @property
    def IsSwitch(self) -> bool: ...
