__all__ = ['Providers']
from typing import Tuple, Set, Iterable, List


class ClientFormsIdentity(Object):
    def __init__(self, name: str, password: str, provider: MembershipProvider, authenticationType: str, isAuthenticated: bool, authenticationCookies: CookieContainer): ...
    def Dispose(self) -> None: ...
    @property
    def AuthenticationCookies(self) -> CookieContainer: ...
    @property
    def AuthenticationType(self) -> str: ...
    @property
    def IsAuthenticated(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Provider(self) -> MembershipProvider: ...
    def RevalidateUser(self) -> None: ...


class ClientRolePrincipal(Object):
    def __init__(self, identity: IIdentity): ...
    @property
    def Identity(self) -> IIdentity: ...
    def IsInRole(self, role: str) -> bool: ...


class ConnectivityStatus(Object):
    @property
    def IsOffline() -> bool: ...
    @IsOffline.setter
    def IsOffline(value: bool) -> None: ...
