from typing import Tuple, Set, Iterable, List


class ISymbolVariable:
    @property
    def AddressField1(self) -> int: ...
    @property
    def AddressField2(self) -> int: ...
    @property
    def AddressField3(self) -> int: ...
    @property
    def AddressKind(self) -> SymAddressKind: ...
    @property
    def Attributes(self) -> Object: ...
    @property
    def EndOffset(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def StartOffset(self) -> int: ...
    def GetSignature(self) -> Set(Byte): ...
