from typing import Tuple, Set, Iterable, List


class FileTypeAction(PolicyMakerElement):
    def __init__(self): ...


class FileTypeOptionsGPOSetting(FolderOptionsGPOSettingBase):
    def __init__(self): ...
    def GetHashKey(self) -> str: ...


class FolderOptionFilter(PolicyMakerElement):
    def __init__(self): ...


class FolderOptionProperties(PolicyMakerProperties):
    def __init__(self): ...
    @property
    def Actions(self) -> Collection: ...
    @Actions.setter
    def Actions(self, value: Collection) -> None: ...


class FolderOptionsGPOSettingBase:
    pass


class FolderOptionsGPOSettings(PolicyMakerElement):
    def __init__(self): ...
    @property
    def FolderOptionsSettingsList(self) -> Collection: ...
    @FolderOptionsSettingsList.setter
    def FolderOptionsSettingsList(self, value: Collection) -> None: ...


class FolderOptionsRsopSetting(PolicyMakerRsopSetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, managementObject: ManagementObject): ...
    def GetHashKey(self) -> str: ...
    def GetItemSubInstanceAttributeName(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...
    def IsVistaSetting(self) -> bool: ...


class FolderOptionsSettings(PolicyMakerSettings):
    def __init__(self): ...
    @property
    def FolderOptionsGPOSettings(self) -> FolderOptionsGPOSettings: ...
    @property
    def FolderOptionsRsopSettings(self) -> Collection: ...
    def GetGPOSettings(self) -> ICollection: ...
    def GetRsopSettings(self) -> ICollection: ...
    def Initialize(self, context: ReportingContext) -> None: ...
    @FolderOptionsGPOSettings.setter
    def FolderOptionsGPOSettings(self, value: FolderOptionsGPOSettings) -> None: ...
    @FolderOptionsRsopSettings.setter
    def FolderOptionsRsopSettings(self, value: Collection) -> None: ...


class GlobalFolderOptionsGPOSetting(FolderOptionsGPOSettingBase):
    def __init__(self): ...
    def GetHashKey(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...


class GlobalFolderOptionsVistaGPOSetting(FolderOptionsGPOSettingBase):
    def __init__(self): ...
    def GetHashKey(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...


class OpenWithOptionsGPOSetting(FolderOptionsGPOSettingBase):
    def __init__(self): ...
    def GetHashKey(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...
