from typing import Tuple, Set, Iterable, List


class ArrayEditor(CollectionEditor):
    def __init__(self, type: Type): ...


class CollectionEditor(UITypeEditor):
    def __init__(self, type: Type): ...
    @overload
    def EditValue(self, context: ITypeDescriptorContext, provider: IServiceProvider, value: Object) -> Object: ...
    @overload
    def GetEditStyle(self, context: ITypeDescriptorContext) -> UITypeEditorEditStyle: ...


class DateTimeEditor(UITypeEditor):
    def __init__(self): ...
    @overload
    def EditValue(self, context: ITypeDescriptorContext, provider: IServiceProvider, value: Object) -> Object: ...
    @overload
    def GetEditStyle(self, context: ITypeDescriptorContext) -> UITypeEditorEditStyle: ...


class MultilineStringEditor(UITypeEditor):
    def __init__(self): ...
    @overload
    def EditValue(self, context: ITypeDescriptorContext, provider: IServiceProvider, value: Object) -> Object: ...
    @overload
    def GetEditStyle(self, context: ITypeDescriptorContext) -> UITypeEditorEditStyle: ...
    @overload
    def GetPaintValueSupported(self, context: ITypeDescriptorContext) -> bool: ...


class ObjectSelectorEditor(UITypeEditor):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, subObjectSelector: bool): ...
    def ApplyTreeViewThemeStyles(treeView: TreeView) -> None: ...
    @overload
    def EditValue(self, context: ITypeDescriptorContext, provider: IServiceProvider, value: Object) -> Object: ...
    @overload
    def GetEditStyle(self, context: ITypeDescriptorContext) -> UITypeEditorEditStyle: ...
    def SetValue(self, value: Object) -> None: ...


class Selector(TreeView):
    def __init__(self, editor: ObjectSelectorEditor): ...
    def AddNode(self, label: str, value: Object, parent: SelectorNode) -> SelectorNode: ...
    def Clear(self) -> None: ...
    def SetSelection(self, value: Object, nodes: TreeNodeCollection) -> bool: ...
    def Start(self, edSvc: IWindowsFormsEditorService, value: Object) -> None: ...
    def Stop(self) -> None: ...


class SelectorNode(TreeNode):
    def __init__(self, label: str, value: Object): ...
