from typing import Tuple, Set, Iterable, List


class UserConfiguredWindows8App:
    def __init__(self, packageFamilyName: str): ...
    def CheckApp(packageFamilyName: str) -> bool: ...
    def DisableApp(packageFamilyName: str) -> None: ...
    def EnableApp(packageFamilyName: str) -> None: ...
    def EnumerateAppPackages() -> IEnumerable: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def Enabled(self) -> bool: ...
    @property
    def Installed(self) -> bool: ...
    @property
    def PackageFamilyName(self) -> str: ...
    def RemoveApp(packageFamilyName: str) -> None: ...
