from typing import Tuple, Set, Iterable, List


class MsmqIntegrationBinding(MsmqBindingBase):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, configurationName: str): ...
    @overload
    def __init__(self, securityMode: MsmqIntegrationSecurityMode): ...
    def CreateBindingElements(self) -> BindingElementCollection: ...
    @property
    def Security(self) -> MsmqIntegrationSecurity: ...
    @property
    def SerializationFormat(self) -> MsmqMessageSerializationFormat: ...
    @Security.setter
    def Security(self, value: MsmqIntegrationSecurity) -> None: ...
    @SerializationFormat.setter
    def SerializationFormat(self, value: MsmqMessageSerializationFormat) -> None: ...
    def ShouldSerializeSecurity(self) -> bool: ...


class MsmqIntegrationBindingElement(MsmqBindingElementBase):
    def __init__(self): ...
    def BuildChannelFactory(self, context: BindingContext) -> IChannelFactory: ...
    def BuildChannelListener(self, context: BindingContext) -> IChannelListener: ...
    def CanBuildChannelFactory(self, context: BindingContext) -> bool: ...
    def CanBuildChannelListener(self, context: BindingContext) -> bool: ...
    def Clone(self) -> BindingElement: ...
    @property
    def Scheme(self) -> str: ...
    @property
    def SerializationFormat(self) -> MsmqMessageSerializationFormat: ...
    @property
    def TargetSerializationTypes(self) -> Set(Type): ...
    def GetProperty(self, context: BindingContext) -> T: ...
    @SerializationFormat.setter
    def SerializationFormat(self, value: MsmqMessageSerializationFormat) -> None: ...
    @TargetSerializationTypes.setter
    def TargetSerializationTypes(self, value: Set(Type)) -> None: ...


class MsmqIntegrationMessageProperty(Object):
    def __init__(self): ...
    @property
    def AcknowledgeType(self) -> Nullable: ...
    @property
    def Acknowledgment(self) -> Nullable: ...
    @property
    def AdministrationQueue(self) -> Uri: ...
    @property
    def AppSpecific(self) -> Nullable: ...
    @property
    def ArrivedTime(self) -> Nullable: ...
    @property
    def Authenticated(self) -> Nullable: ...
    @property
    def Body(self) -> Object: ...
    @property
    def BodyType(self) -> Nullable: ...
    @property
    def CorrelationId(self) -> str: ...
    @property
    def DestinationQueue(self) -> Uri: ...
    @property
    def Extension(self) -> Set(Byte): ...
    @property
    def Id(self) -> str: ...
    @property
    def Label(self) -> str: ...
    @property
    def MessageType(self) -> Nullable: ...
    @property
    def Priority(self) -> Nullable: ...
    @property
    def ResponseQueue(self) -> Uri: ...
    def Get(message: Message) -> MsmqIntegrationMessageProperty: ...
    @property
    def SenderId(self) -> Set(Byte): ...
    @property
    def SentTime(self) -> Nullable: ...
    @property
    def TimeToReachQueue(self) -> Nullable: ...
    @AcknowledgeType.setter
    def AcknowledgeType(self, value: Nullable) -> None: ...
    @AdministrationQueue.setter
    def AdministrationQueue(self, value: Uri) -> None: ...
    @AppSpecific.setter
    def AppSpecific(self, value: Nullable) -> None: ...
    @Body.setter
    def Body(self, value: Object) -> None: ...
    @BodyType.setter
    def BodyType(self, value: Nullable) -> None: ...
    @CorrelationId.setter
    def CorrelationId(self, value: str) -> None: ...
    @Extension.setter
    def Extension(self, value: Set(Byte)) -> None: ...
    @Label.setter
    def Label(self, value: str) -> None: ...
    @Priority.setter
    def Priority(self, value: Nullable) -> None: ...
    @ResponseQueue.setter
    def ResponseQueue(self, value: Uri) -> None: ...
    @TimeToReachQueue.setter
    def TimeToReachQueue(self, value: Nullable) -> None: ...


class MsmqIntegrationSecurity(Object):
    def __init__(self): ...
    @property
    def Mode(self) -> MsmqIntegrationSecurityMode: ...
    @property
    def Transport(self) -> MsmqTransportSecurity: ...
    @Mode.setter
    def Mode(self, value: MsmqIntegrationSecurityMode) -> None: ...
    @Transport.setter
    def Transport(self, value: MsmqTransportSecurity) -> None: ...


class MsmqIntegrationSecurityMode:
    #None = 0
    Transport = 1




class MsmqMessageSerializationFormat:
    Xml = 0
    Binary = 1
    ActiveX = 2
    ByteArray = 3
    Stream = 4
