from typing import Tuple, Set, Iterable, List


class IISServerAuthenticationHandler:
    def __init__(self): ...
    def AuthenticateAsync(self) -> Task: ...
    def ChallengeAsync(self, properties: AuthenticationProperties) -> Task: ...
    def ForbidAsync(self, properties: AuthenticationProperties) -> Task: ...
    def InitializeAsync(self, scheme: AuthenticationScheme, context: HttpContext) -> Task: ...


class ThrowingWasUpgradedWriteOnlyStream(WriteOnlyStream):
    def __init__(self): ...
    def Flush(self) -> None: ...
    def Seek(self, offset: Int64, origin: SeekOrigin) -> Int64: ...
    def SetLength(self, value: Int64) -> None: ...
    @overload
    def Write(self, buffer: Set(Byte), offset: int, count: int) -> None: ...
    @overload
    def WriteAsync(self, buffer: Set(Byte), offset: int, count: int, cancellationToken: CancellationToken) -> Task: ...


class WriteOnlyStream:
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanSeek(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    @property
    def Length(self) -> Int64: ...
    @property
    def Position(self) -> Int64: ...
    @property
    def ReadTimeout(self) -> int: ...
    @overload
    def Read(self, buffer: Set(Byte), offset: int, count: int) -> int: ...
    @overload
    def ReadAsync(self, buffer: Set(Byte), offset: int, count: int, cancellationToken: CancellationToken) -> Task: ...
    def Seek(self, offset: Int64, origin: SeekOrigin) -> Int64: ...
    @Position.setter
    def Position(self, value: Int64) -> None: ...
    @ReadTimeout.setter
    def ReadTimeout(self, value: int) -> None: ...
    def SetLength(self, value: Int64) -> None: ...
