from typing import Tuple, Set, Iterable, List


class IPAddressCollection(Object):
    def Add(self, address: IPAddress) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, address: IPAddress) -> bool: ...
    def CopyTo(self, array: Set(IPAddress), offset: int) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def IsReadOnly(self) -> bool: ...
    @property
    def Item(self, index: int) -> IPAddress: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def Remove(self, address: IPAddress) -> bool: ...
