from typing import Tuple, Set, Iterable, List


class GeneratorPosition:
    def __init__(self, index: int, offset: int): ...
    def Equals(self, o: Object) -> bool: ...
    @property
    def Index(self) -> int: ...
    @property
    def Offset(self) -> int: ...
    def GetHashCode(self) -> int: ...
    def op_Equality(gp1: GeneratorPosition, gp2: GeneratorPosition) -> bool: ...
    def op_Inequality(gp1: GeneratorPosition, gp2: GeneratorPosition) -> bool: ...
    @Index.setter
    def Index(self, value: int) -> None: ...
    @Offset.setter
    def Offset(self, value: int) -> None: ...
    def ToString(self) -> str: ...
