from typing import Tuple, Set, Iterable, List


class W3CLoggerOptions:
    def __init__(self): ...
    @property
    def FileName(self) -> str: ...
    @property
    def FileSizeLimit(self) -> Nullable: ...
    @property
    def FlushInterval(self) -> TimeSpan: ...
    @property
    def LogDirectory(self) -> str: ...
    @property
    def LoggingFields(self) -> W3CLoggingFields: ...
    @property
    def RetainedFileCountLimit(self) -> Nullable: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @FileSizeLimit.setter
    def FileSizeLimit(self, value: Nullable) -> None: ...
    @FlushInterval.setter
    def FlushInterval(self, value: TimeSpan) -> None: ...
    @LogDirectory.setter
    def LogDirectory(self, value: str) -> None: ...
    @LoggingFields.setter
    def LoggingFields(self, value: W3CLoggingFields) -> None: ...
    @RetainedFileCountLimit.setter
    def RetainedFileCountLimit(self, value: Nullable) -> None: ...
