from typing import Tuple, Set, Iterable, List


class NavLink(ComponentBase):
    def __init__(self): ...
    def Dispose(self) -> None: ...
    @property
    def ActiveClass(self) -> str: ...
    @property
    def AdditionalAttributes(self) -> IReadOnlyDictionary: ...
    @property
    def ChildContent(self) -> RenderFragment: ...
    @property
    def Match(self) -> NavLinkMatch: ...
    @ActiveClass.setter
    def ActiveClass(self, value: str) -> None: ...
    @AdditionalAttributes.setter
    def AdditionalAttributes(self, value: IReadOnlyDictionary) -> None: ...
    @ChildContent.setter
    def ChildContent(self, value: RenderFragment) -> None: ...
    @Match.setter
    def Match(self, value: NavLinkMatch) -> None: ...


class NavLinkMatch:
    Prefix = 0
    All = 1
