from typing import Tuple, Set, Iterable, List


class XmlDataIslandsMainSectionTemplate(XmlDataIslandTemplate):
    def __init__(self): ...
    @property
    def ComputerPolicySection(self) -> PolicySectionTemplate: ...
    @property
    def Label(self) -> Set(Label): ...
    @property
    def UserPolicySection(self) -> PolicySectionTemplate: ...
    @ComputerPolicySection.setter
    def ComputerPolicySection(self, value: PolicySectionTemplate) -> None: ...
    @Label.setter
    def Label(self, value: Set(Label)) -> None: ...
    @UserPolicySection.setter
    def UserPolicySection(self, value: PolicySectionTemplate) -> None: ...
