from typing import Tuple, Set, Iterable, List


class JsonContent(HttpContent):
    @overload
    def Create(inputValue: T, mediaType: MediaTypeHeaderValue, options: JsonSerializerOptions) -> JsonContent: ...
    @overload
    def Create(inputValue: Object, inputType: Type, mediaType: MediaTypeHeaderValue, options: JsonSerializerOptions) -> JsonContent: ...
    @property
    def ObjectType(self) -> Type: ...
    @property
    def Value(self) -> Object: ...
