from typing import Tuple, Set, Iterable, List


class IX509Certificate2:
    @property
    def FriendlyName(self) -> str: ...
    @property
    def Issuer(self) -> str: ...
    @property
    def NotAfter(self) -> DateTime: ...
    @property
    def NotBefore(self) -> DateTime: ...
    @property
    def OaasPublicKey(self) -> str: ...
    @property
    def RawData(self) -> Set(Byte): ...
    @property
    def Subject(self) -> str: ...
    @property
    def Thumbprint(self) -> str: ...
    @property
    def Version(self) -> int: ...
