from typing import Tuple, Set, Iterable, List


class FolderGPOSetting:
    def __init__(self): ...
    def GetHashKey(self) -> str: ...


class FoldersGPOSettings(PolicyMakerElement):
    def __init__(self): ...
    @property
    def FoldersSettingsList(self) -> Collection: ...
    @FoldersSettingsList.setter
    def FoldersSettingsList(self, value: Collection) -> None: ...


class FoldersRsopSetting(PolicyMakerRsopSetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, managementObject: ManagementObject): ...
    def GetHashKey(self) -> str: ...
    def GetItemSubInstanceAttributeName(self) -> str: ...
    def GetPath(self) -> str: ...


class FoldersSettings(PolicyMakerSettings):
    def __init__(self): ...
    @property
    def FoldersGPOSettings(self) -> FoldersGPOSettings: ...
    @property
    def FoldersRsopSettings(self) -> Collection: ...
    def GetGPOSettings(self) -> ICollection: ...
    def GetRsopSettings(self) -> ICollection: ...
    def Initialize(self, context: ReportingContext) -> None: ...
    @FoldersGPOSettings.setter
    def FoldersGPOSettings(self, value: FoldersGPOSettings) -> None: ...
    @FoldersRsopSettings.setter
    def FoldersRsopSettings(self, value: Collection) -> None: ...
