__all__ = ['Format','Format','Format','Format']
from typing import Tuple, Set, Iterable, List


class TransactedRegistrySecurity:
    def __init__(self): ...
    def AccessRuleFactory(self, identityReference: IdentityReference, accessMask: int, isInherited: bool, inheritanceFlags: InheritanceFlags, propagationFlags: PropagationFlags, type: AccessControlType) -> AccessRule: ...
    def AddAccessRule(self, rule: TransactedRegistryAccessRule) -> None: ...
    def AddAuditRule(self, rule: TransactedRegistryAuditRule) -> None: ...
    def AuditRuleFactory(self, identityReference: IdentityReference, accessMask: int, isInherited: bool, inheritanceFlags: InheritanceFlags, propagationFlags: PropagationFlags, flags: AuditFlags) -> AuditRule: ...
    @property
    def AccessRightType(self) -> Type: ...
    @property
    def AccessRuleType(self) -> Type: ...
    @property
    def AuditRuleType(self) -> Type: ...
    def RemoveAccessRule(self, rule: TransactedRegistryAccessRule) -> bool: ...
    def RemoveAccessRuleAll(self, rule: TransactedRegistryAccessRule) -> None: ...
    def RemoveAccessRuleSpecific(self, rule: TransactedRegistryAccessRule) -> None: ...
    def RemoveAuditRule(self, rule: TransactedRegistryAuditRule) -> bool: ...
    def RemoveAuditRuleAll(self, rule: TransactedRegistryAuditRule) -> None: ...
    def RemoveAuditRuleSpecific(self, rule: TransactedRegistryAuditRule) -> None: ...
    def ResetAccessRule(self, rule: TransactedRegistryAccessRule) -> None: ...
    def SetAccessRule(self, rule: TransactedRegistryAccessRule) -> None: ...
    def SetAuditRule(self, rule: TransactedRegistryAuditRule) -> None: ...
