from typing import Tuple, Set, Iterable, List


class DataMemberRequiredBindingMetadataProvider:
    def __init__(self): ...
    def CreateBindingMetadata(self, context: BindingMetadataProviderContext) -> None: ...
