__all__ = ['Resolvers','Resolvers','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','Serialization','XmlConfiguration','XmlConfiguration','XPath','XPath','XPath','XPath','XPath','XPath','XPath','XPath','XPath','XPath','XPath','XPath','XPath','Xsl','Xsl','Xsl','Xsl','Xsl','Xsl','Xsl','Xsl','Xsl','Xsl','Xsl']
from typing import Tuple, Set, Iterable, List


class XmlWhitespace(XmlCharacterData):
    def CloneNode(self, deep: bool) -> XmlNode: ...
    @property
    def LocalName(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def NodeType(self) -> XmlNodeType: ...
    @property
    def ParentNode(self) -> XmlNode: ...
    @property
    def PreviousText(self) -> XmlNode: ...
    @property
    def Value(self) -> str: ...
    @Value.setter
    def Value(self, value: str) -> None: ...
    def WriteContentTo(self, w: XmlWriter) -> None: ...
    def WriteTo(self, w: XmlWriter) -> None: ...
