from typing import Tuple, Set, Iterable, List


class ServerComputer:
    def __init__(self): ...
    @property
    def Clock(self) -> Clock: ...
    @property
    def FileSystem(self) -> FileSystemProxy: ...
    @property
    def Info(self) -> ComputerInfo: ...
    @property
    def Name(self) -> str: ...
    @property
    def Network(self) -> Network: ...
    @property
    def Registry(self) -> RegistryProxy: ...
