from typing import Tuple, Set, Iterable, List


class IInternetProperty:
    @property
    def Disabled(self) -> bool: ...
    @property
    def Id(self) -> str: ...
    @property
    def Value(self) -> str: ...
    @Id.setter
    def Id(self, value: str) -> None: ...
    @Value.setter
    def Value(self, value: str) -> None: ...


class InternetGPOSetting:
    def __init__(self): ...
    @property
    def InternetExplorer10Setting(self) -> bool: ...
    @property
    def InternetExplorer7Setting(self) -> bool: ...
    @property
    def InternetExplorer8Setting(self) -> bool: ...
    def GetHashKey(self) -> str: ...
    def IsDisabled(self) -> bool: ...


class InternetGPOSettingIE10(InternetGPOSetting):
    def __init__(self): ...
    def ArePopupAllowedSitesEnabled(self) -> bool: ...
    @property
    def InternetExplorer10Setting(self) -> bool: ...
    @property
    def PopupAllowedSitesCollection(self) -> RegistryCollectionGPOSetting: ...
    @PopupAllowedSitesCollection.setter
    def PopupAllowedSitesCollection(self, value: RegistryCollectionGPOSetting) -> None: ...


class InternetGPOSettingIE7(InternetGPOSetting):
    def __init__(self): ...
    def ArePopupAllowedSitesEnabled(self) -> bool: ...
    @property
    def InternetExplorer7Setting(self) -> bool: ...
    @property
    def PopupAllowedSitesCollection(self) -> RegistryCollectionGPOSetting: ...
    @PopupAllowedSitesCollection.setter
    def PopupAllowedSitesCollection(self, value: RegistryCollectionGPOSetting) -> None: ...


class InternetGPOSettingIE8(InternetGPOSetting):
    def __init__(self): ...
    def ArePopupAllowedSitesEnabled(self) -> bool: ...
    @property
    def InternetExplorer8Setting(self) -> bool: ...
    @property
    def PopupAllowedSitesCollection(self) -> RegistryCollectionGPOSetting: ...
    @PopupAllowedSitesCollection.setter
    def PopupAllowedSitesCollection(self, value: RegistryCollectionGPOSetting) -> None: ...


class InternetGPOSettings(PolicyMakerElement):
    def __init__(self): ...
    @property
    def InternetSettings(self) -> Collection: ...
    @InternetSettings.setter
    def InternetSettings(self, value: Collection) -> None: ...


class InternetProperties(PolicyMakerProperties):
    def __init__(self): ...
    @property
    def Settings(self) -> Collection: ...
    def GetAttributeValue(self, attributeName: str) -> str: ...
    @Settings.setter
    def Settings(self, value: Collection) -> None: ...


class InternetRsopSetting(PolicyMakerRsopSetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, managementObject: ManagementObject): ...
    def GetHashKey(self) -> str: ...
    def GetItemName(self) -> str: ...
    def GetItemSubInstanceAttributeName(self) -> str: ...


class InternetSetting(PolicySetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, settingObject: ManagementObject, registryItem: INSTANCERsopXmlElement, settingId: str): ...
    @property
    def BitField(self) -> str: ...
    @property
    def DefaultValue(self) -> str: ...
    @property
    def Disabled(self) -> bool: ...
    @property
    def DisabledAttribute(self) -> str: ...
    @property
    def DisabledAttributeSpecified(self) -> bool: ...
    @property
    def Hive(self) -> str: ...
    @property
    def Id(self) -> str: ...
    @property
    def Key(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def ParentName(self) -> str: ...
    @property
    def SubProperty(self) -> Collection: ...
    @property
    def Type(self) -> str: ...
    @property
    def Value(self) -> str: ...
    @BitField.setter
    def BitField(self, value: str) -> None: ...
    @DefaultValue.setter
    def DefaultValue(self, value: str) -> None: ...
    @DisabledAttribute.setter
    def DisabledAttribute(self, value: str) -> None: ...
    @DisabledAttributeSpecified.setter
    def DisabledAttributeSpecified(self, value: bool) -> None: ...
    @Hive.setter
    def Hive(self, value: str) -> None: ...
    @Id.setter
    def Id(self, value: str) -> None: ...
    @Key.setter
    def Key(self, value: str) -> None: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @ParentName.setter
    def ParentName(self, value: str) -> None: ...
    @SubProperty.setter
    def SubProperty(self, value: Collection) -> None: ...
    @Type.setter
    def Type(self, value: str) -> None: ...
    @Value.setter
    def Value(self, value: str) -> None: ...


class InternetSettings(GPOExtension):
    def __init__(self): ...
    @property
    def FailedRsopSettings(self) -> Collection: ...
    @property
    def InternetGPOSettings(self) -> InternetGPOSettings: ...
    @property
    def WinningRsopSettings(self) -> Collection: ...
    @property
    def WinningRsopSettingsIE7(self) -> Collection: ...
    def Initialize(self, context: ReportingContext) -> None: ...
    @FailedRsopSettings.setter
    def FailedRsopSettings(self, value: Collection) -> None: ...
    @InternetGPOSettings.setter
    def InternetGPOSettings(self, value: InternetGPOSettings) -> None: ...
    @WinningRsopSettings.setter
    def WinningRsopSettings(self, value: Collection) -> None: ...
    @WinningRsopSettingsIE7.setter
    def WinningRsopSettingsIE7(self, value: Collection) -> None: ...


class SubProperty:
    def __init__(self): ...
    @property
    def Disabled(self) -> bool: ...
    @property
    def DisabledAttribute(self) -> str: ...
    @property
    def DisabledAttributeSpecified(self) -> bool: ...
    @property
    def Id(self) -> str: ...
    @property
    def Mask(self) -> str: ...
    @property
    def Value(self) -> str: ...
    @DisabledAttribute.setter
    def DisabledAttribute(self, value: str) -> None: ...
    @DisabledAttributeSpecified.setter
    def DisabledAttributeSpecified(self, value: bool) -> None: ...
    @Id.setter
    def Id(self, value: str) -> None: ...
    @Mask.setter
    def Mask(self, value: str) -> None: ...
    @Value.setter
    def Value(self, value: str) -> None: ...
