from typing import Tuple, Set, Iterable, List


class ViewLocalizer:
    def __init__(self, localizerFactory: IHtmlLocalizerFactory, hostingEnvironment: IWebHostEnvironment): ...
    def Contextualize(self, viewContext: ViewContext) -> None: ...
    @property
    def Item(self, key: str) -> LocalizedHtmlString: ...
    @property
    def Item(self, key: str, arguments: Set(Object)) -> LocalizedHtmlString: ...
    def GetAllStrings(self, includeParentCultures: bool) -> Iterable[LocalizedString]: ...
    @overload
    def GetString(self, name: str) -> LocalizedString: ...
    @overload
    def GetString(self, name: str, values: Set(Object)) -> LocalizedString: ...
