from typing import Tuple, Set, Iterable, List


class PrintingManager(Object):
    def __init__(self, container: IServiceContainer): ...
    def Dispose(self) -> None: ...
    @property
    def PrintDocument(self) -> PrintDocument: ...
    def PageSetup(self) -> None: ...
    def Print(self, showPrintDialog: bool) -> None: ...
    def PrintPaint(self, graphics: Graphics, position: Rectangle) -> None: ...
    def PrintPreview(self) -> None: ...
    @PrintDocument.setter
    def PrintDocument(self, value: PrintDocument) -> None: ...
