from typing import Tuple, Set, Iterable, List


class EFSSettings(PolicySetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, policySetting: PolicySetting, policyAllowEFS: UInt32, policyOptions: UInt32, policyCacheTimeout: UInt32, policyKeyLen: UInt32, policyTemplateName: str): ...
    @property
    def AllowEFS(self) -> UInt32: ...
    @property
    def CacheTimeout(self) -> UInt32: ...
    @property
    def KeyLen(self) -> UInt32: ...
    @property
    def Options(self) -> UInt32: ...
    @property
    def TemplateName(self) -> str: ...
    @AllowEFS.setter
    def AllowEFS(self, value: UInt32) -> None: ...
    @CacheTimeout.setter
    def CacheTimeout(self, value: UInt32) -> None: ...
    @KeyLen.setter
    def KeyLen(self, value: UInt32) -> None: ...
    @Options.setter
    def Options(self, value: UInt32) -> None: ...
    @TemplateName.setter
    def TemplateName(self, value: str) -> None: ...
