from typing import Tuple, Set, Iterable, List


class XsltLibrary(Object):
    def CheckScriptNamespace(self, nsUri: str) -> int: ...
    def ElementAvailable(self, name: XmlQualifiedName) -> bool: ...
    def EqualityOperator(self, opCode: float, left: List[XPathItem], right: List[XPathItem]) -> bool: ...
    def FormatMessage(self, res: str, args: List[str]) -> str: ...
    def FormatNumberDynamic(self, value: float, formatPicture: str, decimalFormatName: XmlQualifiedName, errorMessageName: str) -> str: ...
    def FormatNumberStatic(self, value: float, decimalFormatterIndex: float) -> str: ...
    def FunctionAvailable(self, name: XmlQualifiedName) -> bool: ...
    def IsSameNodeSort(self, nav1: XPathNavigator, nav2: XPathNavigator) -> bool: ...
    def LangToLcid(self, lang: str, forwardCompatibility: bool) -> int: ...
    def NumberFormat(self, value: List[XPathItem], formatString: str, lang: float, letterValue: str, groupingSeparator: str, groupingSize: float) -> str: ...
    def RegisterDecimalFormat(self, name: XmlQualifiedName, infinitySymbol: str, nanSymbol: str, characters: str) -> int: ...
    def RegisterDecimalFormatter(self, formatPicture: str, infinitySymbol: str, nanSymbol: str, characters: str) -> float: ...
    def RelationalOperator(self, opCode: float, left: List[XPathItem], right: List[XPathItem]) -> bool: ...
