from typing import Tuple, Set, Iterable, List


class ForLoopControl:
    def ForLoopInitObj(Counter: Object, Start: Object, Limit: Object, StepValue: Object, LoopForResult: Object, CounterResult: Object) -> Tuple[bool, Object, Object]: ...
    def ForNextCheckDec(count: Decimal, limit: Decimal, StepValue: Decimal) -> bool: ...
    def ForNextCheckObj(Counter: Object, LoopObj: Object, CounterResult: Object) -> Tuple[bool, Object]: ...
    def ForNextCheckR4(count: Single, limit: Single, StepValue: Single) -> bool: ...
    def ForNextCheckR8(count: float, limit: float, StepValue: float) -> bool: ...
