__all__ = ['Activation','Activation','Channels','Channels','Channels','Channels','Channels','Channels','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Description','Description','Description','Description','Description','Description','Dispatcher','Dispatcher','Dispatcher','Web','Web','Web','Web','Web','Web','Web','Web','Web','Web','Web','Web','Web','Web','Web']
from typing import Tuple, Set, Iterable, List


class WebHttpSecurity(Object):
    def __init__(self): ...
    @property
    def Mode(self) -> WebHttpSecurityMode: ...
    @property
    def Transport(self) -> HttpTransportSecurity: ...
    @Mode.setter
    def Mode(self, value: WebHttpSecurityMode) -> None: ...
    @Transport.setter
    def Transport(self, value: HttpTransportSecurity) -> None: ...
    def ShouldSerializeMode(self) -> bool: ...
    def ShouldSerializeTransport(self) -> bool: ...
