from typing import Tuple, Set, Iterable, List


class RegisterCimIndicationCommand(ObjectEventRegistrationBase):
    def __init__(self): ...
    @property
    def CimSession(self) -> CimSession: ...
    @property
    def ClassName(self) -> str: ...
    @property
    def ComputerName(self) -> str: ...
    @property
    def Namespace(self) -> str: ...
    @property
    def OperationTimeoutSec(self) -> UInt32: ...
    @property
    def Query(self) -> str: ...
    @property
    def QueryDialect(self) -> str: ...
    @CimSession.setter
    def CimSession(self, value: CimSession) -> None: ...
    @ClassName.setter
    def ClassName(self, value: str) -> None: ...
    @ComputerName.setter
    def ComputerName(self, value: str) -> None: ...
    @Namespace.setter
    def Namespace(self, value: str) -> None: ...
    @OperationTimeoutSec.setter
    def OperationTimeoutSec(self, value: UInt32) -> None: ...
    @Query.setter
    def Query(self, value: str) -> None: ...
    @QueryDialect.setter
    def QueryDialect(self, value: str) -> None: ...
