from typing import Tuple, Set, Iterable, List


class EQoSSettings(GPOExtension):
    def __init__(self): ...
    @property
    def QoSAppDscpMarkingSetting(self) -> QoSAppDscpMarkingSetting: ...
    @property
    def QoSPolicy(self) -> ArrayList: ...
    @property
    def QoSTCPAutoTuningSetting(self) -> QoSTCPAutoTuningSetting: ...
    @overload
    def Initialize(self, context: ReportingContext) -> None: ...
    @overload
    def Initialize(self, regEqosSettings: ArrayList, context: ReportingContext) -> None: ...
    @QoSAppDscpMarkingSetting.setter
    def QoSAppDscpMarkingSetting(self, value: QoSAppDscpMarkingSetting) -> None: ...
    @QoSPolicy.setter
    def QoSPolicy(self, value: ArrayList) -> None: ...
    @QoSTCPAutoTuningSetting.setter
    def QoSTCPAutoTuningSetting(self, value: QoSTCPAutoTuningSetting) -> None: ...


class QoSAppDscpMarkingSetting(PolicySetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, regSetting: PolicySetting, appDscpMarkingConfiguration: str): ...
    @property
    def AppDscpMarkingConfiguration(self) -> str: ...
    @AppDscpMarkingConfiguration.setter
    def AppDscpMarkingConfiguration(self, value: str) -> None: ...


class QoSPolicy(PolicySetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, regSetting: PolicySetting, policyName: str): ...
    @property
    def ApplicationName(self) -> str: ...
    @property
    def DSCPValue(self) -> str: ...
    @property
    def LocalIPAndPrefix(self) -> str: ...
    @property
    def LocalPort(self) -> str: ...
    @property
    def PolicyName(self) -> str: ...
    @property
    def PolicyVersion(self) -> str: ...
    @property
    def Protocol(self) -> str: ...
    @property
    def RemoteIPAndPrefix(self) -> str: ...
    @property
    def RemotePort(self) -> str: ...
    @property
    def Resource(self) -> str: ...
    @property
    def ResourceRecursive(self) -> Nullable: ...
    @property
    def ThrottleRate(self) -> str: ...
    @ApplicationName.setter
    def ApplicationName(self, value: str) -> None: ...
    @DSCPValue.setter
    def DSCPValue(self, value: str) -> None: ...
    @LocalIPAndPrefix.setter
    def LocalIPAndPrefix(self, value: str) -> None: ...
    @LocalPort.setter
    def LocalPort(self, value: str) -> None: ...
    @PolicyName.setter
    def PolicyName(self, value: str) -> None: ...
    @PolicyVersion.setter
    def PolicyVersion(self, value: str) -> None: ...
    @Protocol.setter
    def Protocol(self, value: str) -> None: ...
    @RemoteIPAndPrefix.setter
    def RemoteIPAndPrefix(self, value: str) -> None: ...
    @RemotePort.setter
    def RemotePort(self, value: str) -> None: ...
    @Resource.setter
    def Resource(self, value: str) -> None: ...
    @ResourceRecursive.setter
    def ResourceRecursive(self, value: Nullable) -> None: ...
    @ThrottleRate.setter
    def ThrottleRate(self, value: str) -> None: ...


class QoSTCPAutoTuningSetting(PolicySetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, regSetting: PolicySetting, tcpAutoTuningLevel: str): ...
    @property
    def TcpAutoTuningLevel(self) -> str: ...
    @TcpAutoTuningLevel.setter
    def TcpAutoTuningLevel(self, value: str) -> None: ...
