from typing import Tuple, Set, Iterable, List


class ImeCompositionWindowHeightOffset:
    def __init__(self): ...
    @property
    def Default(self) -> float: ...
    @property
    def Key(self) -> EditorOptionKey: ...
