from typing import Tuple, Set, Iterable, List


class XamlAccessLevel(Object):
    @overload
    def AssemblyAccessTo(assembly: Assembly) -> XamlAccessLevel: ...
    @overload
    def AssemblyAccessTo(assemblyName: AssemblyName) -> XamlAccessLevel: ...
    @property
    def AssemblyAccessToAssemblyName(self) -> AssemblyName: ...
    @property
    def PrivateAccessToTypeName(self) -> str: ...
    @overload
    def PrivateAccessTo(type: Type) -> XamlAccessLevel: ...
    @overload
    def PrivateAccessTo(assemblyQualifiedTypeName: str) -> XamlAccessLevel: ...
