from typing import Tuple, Set, Iterable, List


class HidePropertyInOutlineViewAttribute(Attribute):
    def __init__(self): ...


class ShowInOutlineViewAttribute(Attribute):
    def __init__(self): ...
    @property
    def PromotedProperty(self) -> str: ...
    @PromotedProperty.setter
    def PromotedProperty(self, value: str) -> None: ...


class ShowPropertyInOutlineViewAsSiblingAttribute(Attribute):
    def __init__(self): ...


class ShowPropertyInOutlineViewAttribute(Attribute):
    def __init__(self): ...
    @property
    def ChildNodePrefix(self) -> str: ...
    @property
    def CurrentPropertyVisible(self) -> bool: ...
    @property
    def DuplicatedChildNodesVisible(self) -> bool: ...
    @ChildNodePrefix.setter
    def ChildNodePrefix(self, value: str) -> None: ...
    @CurrentPropertyVisible.setter
    def CurrentPropertyVisible(self, value: bool) -> None: ...
    @DuplicatedChildNodesVisible.setter
    def DuplicatedChildNodesVisible(self, value: bool) -> None: ...
