__all__ = ['OAuth']
from typing import Tuple, Set, Iterable, List


class ClaimActionCollectionMapExtensions:
    def DeleteClaim(collection: ClaimActionCollection, claimType: str) -> None: ...
    def DeleteClaims(collection: ClaimActionCollection, claimTypes: Set(str)) -> None: ...
    def MapAll(collection: ClaimActionCollection) -> None: ...
    def MapAllExcept(collection: ClaimActionCollection, exclusions: Set(str)) -> None: ...
    @overload
    def MapCustomJson(collection: ClaimActionCollection, claimType: str, resolver: Func) -> None: ...
    @overload
    def MapCustomJson(collection: ClaimActionCollection, claimType: str, valueType: str, resolver: Func) -> None: ...
    @overload
    def MapJsonKey(collection: ClaimActionCollection, claimType: str, jsonKey: str) -> None: ...
    @overload
    def MapJsonKey(collection: ClaimActionCollection, claimType: str, jsonKey: str, valueType: str) -> None: ...
    @overload
    def MapJsonSubKey(collection: ClaimActionCollection, claimType: str, jsonKey: str, subKey: str) -> None: ...
    @overload
    def MapJsonSubKey(collection: ClaimActionCollection, claimType: str, jsonKey: str, subKey: str, valueType: str) -> None: ...
