from typing import Tuple, Set, Iterable, List


class NetworkControllerCmdletAdapter(ODataCmdletAdapter):
    def __init__(self): ...
    @property
    def AllowAdditionalData(self) -> SwitchParameter: ...
    @property
    def AllowUnsecureConnection(self) -> SwitchParameter: ...
    @property
    def ConnectionUri(self) -> Uri: ...
    @property
    def CustomUriSuffix(self) -> str: ...
    @property
    def Headers(self) -> Hashtable: ...
    def GetCustomUriHelper(self, defaultUri: str, connectionUri: Uri, keys: List) -> str: ...
    def GetODataReferenceByKeys(self, keys: List) -> str: ...
    def GetUri(self, keys: List) -> str: ...
    @overload
    def ProcessRecord(self, methodInvocationInfo: MethodInvocationInfo) -> None: ...
    @overload
    def ProcessRecord(self, query: QueryBuilder) -> None: ...
    @ConnectionUri.setter
    def ConnectionUri(self, value: Uri) -> None: ...
    @CustomUriSuffix.setter
    def CustomUriSuffix(self, value: str) -> None: ...
    @Headers.setter
    def Headers(self, value: Hashtable) -> None: ...


class ODataCmdletAdapter:
    def __init__(self): ...
    @property
    def AllowAdditionalData(self) -> SwitchParameter: ...
    @property
    def AllowUnsecureConnection(self) -> SwitchParameter: ...
    @property
    def CertificateThumbprint(self) -> str: ...
    @property
    def ConnectionUri(self) -> Uri: ...
    @property
    def Credential(self) -> PSCredential: ...
    @property
    def Headers(self) -> Hashtable: ...
    @property
    def PassInnerException(self) -> SwitchParameter: ...
    def GetCustomUriHelper(self, defaultUri: str, connectionUri: Uri, keys: List) -> str: ...
    def GetODataReferenceByKeys(self, keys: List) -> str: ...
    def GetQueryBuilder(self) -> QueryBuilder: ...
    @overload
    def ProcessRecord(self, methodInvocationInfo: MethodInvocationInfo) -> None: ...
    @overload
    def ProcessRecord(self, query: QueryBuilder) -> None: ...
    @AllowAdditionalData.setter
    def AllowAdditionalData(self, value: SwitchParameter) -> None: ...
    @AllowUnsecureConnection.setter
    def AllowUnsecureConnection(self, value: SwitchParameter) -> None: ...
    @CertificateThumbprint.setter
    def CertificateThumbprint(self, value: str) -> None: ...
    @ConnectionUri.setter
    def ConnectionUri(self, value: Uri) -> None: ...
    @Credential.setter
    def Credential(self, value: PSCredential) -> None: ...
    @Headers.setter
    def Headers(self, value: Hashtable) -> None: ...
    @PassInnerException.setter
    def PassInnerException(self, value: SwitchParameter) -> None: ...


class ODataQueryBuilder(QueryBuilder):
    def __init__(self): ...
    def FilterByProperty(self, propertyName: str, allowedPropertyValues: IEnumerable, wildcardsEnabled: bool, behaviorOnNoMatch: BehaviorOnNoMatch) -> None: ...
    @property
    def Keys(self) -> List: ...
    @Keys.setter
    def Keys(self, value: List) -> None: ...


class ODataV4CmdletAdapter(ODataCmdletAdapter):
    def __init__(self): ...
    def GetODataReferenceByKeys(self, keys: List) -> str: ...
