from typing import Tuple, Set, Iterable, List


class ODataQueryBuilder(QueryBuilder):
    def __init__(self): ...
    def FilterByProperty(self, propertyName: str, allowedPropertyValues: IEnumerable, wildcardsEnabled: bool, behaviorOnNoMatch: BehaviorOnNoMatch) -> None: ...
    @property
    def Keys(self) -> List: ...
    @Keys.setter
    def Keys(self, value: List) -> None: ...
