from typing import Tuple, Set, Iterable, List


class ZipFileExtensions(Object):
    @overload
    def CreateEntryFromFile(destination: ZipArchive, sourceFileName: str, entryName: str) -> ZipArchiveEntry: ...
    @overload
    def CreateEntryFromFile(destination: ZipArchive, sourceFileName: str, entryName: str, compressionLevel: CompressionLevel) -> ZipArchiveEntry: ...
    @overload
    def ExtractToDirectory(source: ZipArchive, destinationDirectoryName: str) -> None: ...
    @overload
    def ExtractToDirectory(source: ZipArchive, destinationDirectoryName: str, overwriteFiles: bool) -> None: ...
    @overload
    def ExtractToFile(source: ZipArchiveEntry, destinationFileName: str) -> None: ...
    @overload
    def ExtractToFile(source: ZipArchiveEntry, destinationFileName: str, overwrite: bool) -> None: ...
