from typing import Tuple, Set, Iterable, List


class Application(Object):
    pass


class ContentDisposition(Object):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, disposition: str): ...
    def Equals(self, rparam: Object) -> bool: ...
    @property
    def CreationDate(self) -> DateTime: ...
    @property
    def DispositionType(self) -> str: ...
    @property
    def FileName(self) -> str: ...
    @property
    def Inline(self) -> bool: ...
    @property
    def ModificationDate(self) -> DateTime: ...
    @property
    def Parameters(self) -> StringDictionary: ...
    @property
    def ReadDate(self) -> DateTime: ...
    @property
    def Size(self) -> Int64: ...
    def GetHashCode(self) -> int: ...
    @CreationDate.setter
    def CreationDate(self, value: DateTime) -> None: ...
    @DispositionType.setter
    def DispositionType(self, value: str) -> None: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @Inline.setter
    def Inline(self, value: bool) -> None: ...
    @ModificationDate.setter
    def ModificationDate(self, value: DateTime) -> None: ...
    @ReadDate.setter
    def ReadDate(self, value: DateTime) -> None: ...
    @Size.setter
    def Size(self, value: Int64) -> None: ...
    def ToString(self) -> str: ...


class ContentType(Object):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, contentType: str): ...
    def Equals(self, rparam: Object) -> bool: ...
    @property
    def Boundary(self) -> str: ...
    @property
    def CharSet(self) -> str: ...
    @property
    def MediaType(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Parameters(self) -> StringDictionary: ...
    def GetHashCode(self) -> int: ...
    @Boundary.setter
    def Boundary(self, value: str) -> None: ...
    @CharSet.setter
    def CharSet(self, value: str) -> None: ...
    @MediaType.setter
    def MediaType(self, value: str) -> None: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    def ToString(self) -> str: ...


class DispositionTypeNames(Object):
    pass


class Image(Object):
    pass


class MediaTypeNames(Object):
    pass


class Text(Object):
    pass


class TransferEncoding:
    QuotedPrintable = 0
    Base64 = 1
    SevenBit = 2
    EightBit = 3
    Unknown = -1
