from typing import Tuple, Set, Iterable, List


class RegistryXmlRepository:
    def __init__(self, registryKey: RegistryKey, loggerFactory: ILoggerFactory): ...
    @property
    def DefaultRegistryKey() -> RegistryKey: ...
    @property
    def RegistryKey(self) -> RegistryKey: ...
    def GetAllElements(self) -> IReadOnlyCollection: ...
    def StoreElement(self, element: XElement, friendlyName: str) -> None: ...
