from typing import Tuple, Set, Iterable, List


class XData(Object):
    def __init__(self): ...
    @property
    def Text(self) -> str: ...
    @property
    def XmlReader(self) -> Object: ...
    @Text.setter
    def Text(self, value: str) -> None: ...
    @XmlReader.setter
    def XmlReader(self, value: Object) -> None: ...
