from typing import Tuple, Set, Iterable, List


class AspNetHostingPermissionAttribute(CodeAccessSecurityAttribute):
    def __init__(self, action: SecurityAction): ...
    def CreatePermission(self) -> IPermission: ...
    @property
    def Level(self) -> AspNetHostingPermissionLevel: ...
    @Level.setter
    def Level(self, value: AspNetHostingPermissionLevel) -> None: ...
