from typing import Tuple, Set, Iterable, List


class AspNetHostingPermission(CodeAccessPermission):
    @overload
    def __init__(self, state: PermissionState): ...
    @overload
    def __init__(self, level: AspNetHostingPermissionLevel): ...
    def Copy(self) -> IPermission: ...
    def FromXml(self, securityElement: SecurityElement) -> None: ...
    @property
    def Level(self) -> AspNetHostingPermissionLevel: ...
    def Intersect(self, target: IPermission) -> IPermission: ...
    def IsSubsetOf(self, target: IPermission) -> bool: ...
    def IsUnrestricted(self) -> bool: ...
    @Level.setter
    def Level(self, value: AspNetHostingPermissionLevel) -> None: ...
    def ToXml(self) -> SecurityElement: ...
    def Union(self, target: IPermission) -> IPermission: ...


class AspNetHostingPermissionAttribute(CodeAccessSecurityAttribute):
    def __init__(self, action: SecurityAction): ...
    def CreatePermission(self) -> IPermission: ...
    @property
    def Level(self) -> AspNetHostingPermissionLevel: ...
    @Level.setter
    def Level(self, value: AspNetHostingPermissionLevel) -> None: ...


class AspNetHostingPermissionLevel:
    #None = 100
    Minimal = 200
    Low = 300
    Medium = 400
    High = 500
    Unrestricted = 600
