__all__ = ['Abstractions','Features']
from typing import Tuple, Set, Iterable, List




class IServer:
    @property
    def Features(self) -> IFeatureCollection: ...
    def StartAsync(self, application: IHttpApplication, cancellationToken: CancellationToken) -> Task: ...
    def StopAsync(self, cancellationToken: CancellationToken) -> Task: ...


class IServerIntegratedAuth:
    @property
    def AuthenticationScheme(self) -> str: ...
    @property
    def IsEnabled(self) -> bool: ...


class ServerIntegratedAuth:
    def __init__(self): ...
    @property
    def AuthenticationScheme(self) -> str: ...
    @property
    def IsEnabled(self) -> bool: ...
    @AuthenticationScheme.setter
    def AuthenticationScheme(self, value: str) -> None: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> None: ...
