from typing import Tuple, Set, Iterable, List


class JsonReaderWriterFactory(Object):
    @overload
    def CreateJsonReader(stream: Stream, quotas: XmlDictionaryReaderQuotas) -> XmlDictionaryReader: ...
    @overload
    def CreateJsonReader(buffer: Set(Byte), quotas: XmlDictionaryReaderQuotas) -> XmlDictionaryReader: ...
    @overload
    def CreateJsonReader(stream: Stream, encoding: Encoding, quotas: XmlDictionaryReaderQuotas, onClose: OnXmlDictionaryReaderClose) -> XmlDictionaryReader: ...
    @overload
    def CreateJsonReader(buffer: Set(Byte), offset: int, count: int, quotas: XmlDictionaryReaderQuotas) -> XmlDictionaryReader: ...
    @overload
    def CreateJsonReader(buffer: Set(Byte), offset: int, count: int, encoding: Encoding, quotas: XmlDictionaryReaderQuotas, onClose: OnXmlDictionaryReaderClose) -> XmlDictionaryReader: ...
    @overload
    def CreateJsonWriter(stream: Stream) -> XmlDictionaryWriter: ...
    @overload
    def CreateJsonWriter(stream: Stream, encoding: Encoding) -> XmlDictionaryWriter: ...
    @overload
    def CreateJsonWriter(stream: Stream, encoding: Encoding, ownsStream: bool) -> XmlDictionaryWriter: ...
    @overload
    def CreateJsonWriter(stream: Stream, encoding: Encoding, ownsStream: bool, indent: bool) -> XmlDictionaryWriter: ...
    @overload
    def CreateJsonWriter(stream: Stream, encoding: Encoding, ownsStream: bool, indent: bool, indentChars: str) -> XmlDictionaryWriter: ...
