from typing import Tuple, Set, Iterable, List


class RootedPathValidator(ConfigurationValidatorBase):
    def __init__(self): ...
    def CanValidate(self, type: Type) -> bool: ...
    def Validate(self, value: Object) -> None: ...
