from typing import Tuple, Set, Iterable, List


class ScheduledTasksGPOSettings(PolicyMakerElement):
    def __init__(self): ...
    @property
    def ScheduledTasksSettingsList(self) -> Collection: ...
    @ScheduledTasksSettingsList.setter
    def ScheduledTasksSettingsList(self, value: Collection) -> None: ...
