from typing import Tuple, Set, Iterable, List


class RibbonApplicationMenuAutomationPeer(RibbonMenuButtonAutomationPeer):
    def __init__(self, owner: RibbonApplicationMenu): ...


class RibbonAutomationPeer(SelectorAutomationPeer):
    def __init__(self, owner: Ribbon): ...
    def Collapse(self) -> None: ...
    def Expand(self) -> None: ...
    @property
    def ExpandCollapseState(self) -> ExpandCollapseState: ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonButtonAutomationPeer(ButtonAutomationPeer):
    def __init__(self, owner: RibbonButton): ...


class RibbonCheckBoxAutomationPeer(CheckBoxAutomationPeer):
    def __init__(self, owner: RibbonCheckBox): ...


class RibbonComboBoxAutomationPeer(RibbonMenuButtonAutomationPeer):
    def __init__(self, owner: RibbonComboBox): ...
    @property
    def IsReadOnly(self) -> bool: ...
    @property
    def Value(self) -> str: ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...
    def SetValue(self, value: str) -> None: ...


class RibbonContextMenuAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonContextMenu): ...


class RibbonContextualTabGroupAutomationPeer(FrameworkElementAutomationPeer):
    def __init__(self, owner: RibbonContextualTabGroup): ...


class RibbonContextualTabGroupDataAutomationPeer(ItemAutomationPeer):
    def __init__(self, item: Object, owner: RibbonContextualTabGroupItemsControlAutomationPeer): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonContextualTabGroupItemsControlAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonContextualTabGroupItemsControl): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonControlAutomationPeer(FrameworkElementAutomationPeer):
    def __init__(self, owner: FrameworkElement): ...


class RibbonControlDataAutomationPeer(ItemAutomationPeer):
    def __init__(self, item: Object, itemsControlPeer: ItemsControlAutomationPeer): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonControlGroupAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonControlGroup): ...


class RibbonGalleryAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonGallery): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonGalleryCategoryAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonGalleryCategory): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonGalleryCategoryDataAutomationPeer(ItemAutomationPeer):
    def __init__(self, owner: Object, itemsControlAutomationPeer: ItemsControlAutomationPeer): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonGalleryItemAutomationPeer(FrameworkElementAutomationPeer):
    def __init__(self, owner: RibbonGalleryItem): ...


class RibbonGalleryItemDataAutomationPeer(ItemAutomationPeer):
    def __init__(self, owner: Object, itemsControlAutomationPeer: ItemsControlAutomationPeer, parentCategoryDataAutomationPeer: RibbonGalleryCategoryDataAutomationPeer): ...
    @property
    def ParentCategoryDataAutomationPeer(self) -> RibbonGalleryCategoryDataAutomationPeer: ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonGroupAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonGroup): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonGroupDataAutomationPeer(ItemAutomationPeer):
    def __init__(self, item: Object, itemsControlPeer: RibbonTabAutomationPeer): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonGroupHeaderAutomationPeer(FrameworkElementAutomationPeer):
    def __init__(self, owner: FrameworkElement): ...


class RibbonMenuButtonAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonMenuButton): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonMenuItemAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonMenuItem): ...


class RibbonMenuItemDataAutomationPeer(ItemAutomationPeer):
    def __init__(self, item: Object, itemsControlPeer: ItemsControlAutomationPeer): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonQuickAccessToolBarAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonQuickAccessToolBar): ...
    def Collapse(self) -> None: ...
    def Expand(self) -> None: ...
    @property
    def ExpandCollapseState(self) -> ExpandCollapseState: ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonRadioButtonAutomationPeer(RadioButtonAutomationPeer):
    def __init__(self, owner: RibbonRadioButton): ...


class RibbonSeparatorAutomationPeer(SeparatorAutomationPeer):
    def __init__(self, owner: RibbonSeparator): ...


class RibbonSplitButtonAutomationPeer(RibbonMenuButtonAutomationPeer):
    def __init__(self, owner: RibbonSplitButton): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonTabAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonTab): ...


class RibbonTabDataAutomationPeer(SelectorItemAutomationPeer):
    def __init__(self, item: Object, itemsControlPeer: RibbonAutomationPeer): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonTabHeaderAutomationPeer(FrameworkElementAutomationPeer):
    def __init__(self, owner: RibbonTabHeader): ...


class RibbonTabHeaderDataAutomationPeer(ItemAutomationPeer):
    def __init__(self, item: Object, itemsControlPeer: RibbonTabHeaderItemsControlAutomationPeer): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonTabHeaderItemsControlAutomationPeer(ItemsControlAutomationPeer):
    def __init__(self, owner: RibbonTabHeaderItemsControl): ...


class RibbonTextBoxAutomationPeer(TextBoxAutomationPeer):
    def __init__(self, owner: RibbonTextBox): ...
    def GetPattern(self, patternInterface: PatternInterface) -> Object: ...


class RibbonTitleAutomationPeer(FrameworkElementAutomationPeer):
    def __init__(self, owner: FrameworkElement): ...


class RibbonToggleButtonAutomationPeer(ToggleButtonAutomationPeer):
    def __init__(self, owner: RibbonToggleButton): ...


class RibbonToolTipAutomationPeer(ToolTipAutomationPeer):
    def __init__(self, owner: RibbonToolTip): ...


class RibbonTwoLineTextAutomationPeer(FrameworkElementAutomationPeer):
    def __init__(self, owner: RibbonTwoLineText): ...
