from typing import Tuple, Set, Iterable, List


class IHttpHeadersHandler:
    def OnHeader(self, name: ReadOnlySpan, value: ReadOnlySpan) -> None: ...
    def OnHeadersComplete(self, endStream: bool) -> None: ...
    @overload
    def OnStaticIndexedHeader(self, index: int) -> None: ...
    @overload
    def OnStaticIndexedHeader(self, index: int, value: ReadOnlySpan) -> None: ...
