__all__ = ['Xml','Xml','Xml','Xml','Xml','Xml','Xml','Xml','Xml','Xml','Xml','Xml','Xml','Xml','Xml']
from typing import Tuple, Set, Iterable, List


class XmlSerializerOutputFormatter(TextOutputFormatter):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, loggerFactory: ILoggerFactory): ...
    @overload
    def __init__(self, writerSettings: XmlWriterSettings): ...
    @overload
    def __init__(self, writerSettings: XmlWriterSettings, loggerFactory: ILoggerFactory): ...
    @overload
    def CreateXmlWriter(self, writer: TextWriter, xmlWriterSettings: XmlWriterSettings) -> XmlWriter: ...
    @overload
    def CreateXmlWriter(self, context: OutputFormatterWriteContext, writer: TextWriter, xmlWriterSettings: XmlWriterSettings) -> XmlWriter: ...
    @property
    def WrapperProviderFactories(self) -> List[IWrapperProviderFactory]: ...
    @property
    def WriterSettings(self) -> XmlWriterSettings: ...
    @overload
    def WriteResponseBodyAsync(self, context: OutputFormatterWriteContext, selectedEncoding: Encoding) -> Task: ...
