from typing import Tuple, Set, Iterable, List


class DotNetDispatcher:
    def BeginInvokeDotNet(jsRuntime: JSRuntime, invocationInfo: DotNetInvocationInfo, argsJson: str) -> None: ...
    def EndInvokeJS(jsRuntime: JSRuntime, arguments: str) -> None: ...
    def Invoke(jsRuntime: JSRuntime, invocationInfo: DotNetInvocationInfo, argsJson: str) -> Tuple[str, DotNetInvocationInfo]: ...


class DotNetInvocationInfo:
    def __init__(self, assemblyName: str, methodIdentifier: str, dotNetObjectId: Int64, callId: str): ...
    @property
    def AssemblyName(self) -> str: ...
    @property
    def CallId(self) -> str: ...
    @property
    def DotNetObjectId(self) -> Int64: ...
    @property
    def MethodIdentifier(self) -> str: ...


class DotNetInvocationResult:
    @overload
    def __init__(self, result: Object): ...
    @overload
    def __init__(self, exception: Exception, errorKind: str): ...
    @property
    def ErrorKind(self) -> str: ...
    @property
    def Exception(self) -> Exception: ...
    @property
    def Result(self) -> Object: ...
    @property
    def Success(self) -> bool: ...
