from typing import Tuple, Set, Iterable, List


class StartMenuGPOSetting(StartMenuGPOSettingBase):
    def __init__(self): ...
    def GetHashKey(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...


class StartMenuGPOSettingBase:
    pass


class StartMenuGPOSettings(PolicyMakerElement):
    def __init__(self): ...
    @property
    def StartMenus(self) -> Collection: ...
    @StartMenus.setter
    def StartMenus(self, value: Collection) -> None: ...


class StartMenuGPOSettingVista(StartMenuGPOSettingBase):
    def __init__(self): ...
    def GetHashKey(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...


class StartMenuRsopSetting(PolicyMakerRsopSetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, managementObject: ManagementObject): ...
    def GetHashKey(self) -> str: ...
    def GetItemSubInstanceAttributeName(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...
    def IsVistaSetting(self) -> bool: ...


class StartMenuSettings(PolicyMakerSettings):
    def __init__(self): ...
    @property
    def StartMenuGPOSettings(self) -> StartMenuGPOSettings: ...
    @property
    def StartMenuRsopSettings(self) -> Collection: ...
    def GetGPOSettings(self) -> ICollection: ...
    def GetRsopSettings(self) -> ICollection: ...
    def Initialize(self, context: ReportingContext) -> None: ...
    @StartMenuGPOSettings.setter
    def StartMenuGPOSettings(self, value: StartMenuGPOSettings) -> None: ...
    @StartMenuRsopSettings.setter
    def StartMenuRsopSettings(self, value: Collection) -> None: ...
