from typing import Tuple, Set, Iterable, List


class HttpsRedirectionOptions:
    def __init__(self): ...
    @property
    def HttpsPort(self) -> Nullable: ...
    @property
    def RedirectStatusCode(self) -> int: ...
    @HttpsPort.setter
    def HttpsPort(self, value: Nullable) -> None: ...
    @RedirectStatusCode.setter
    def RedirectStatusCode(self, value: int) -> None: ...
