from typing import Tuple, Set, Iterable, List


class FileSystemXmlRepository:
    def __init__(self, directory: DirectoryInfo, loggerFactory: ILoggerFactory): ...
    @property
    def DefaultKeyStorageDirectory() -> DirectoryInfo: ...
    @property
    def Directory(self) -> DirectoryInfo: ...
    def GetAllElements(self) -> IReadOnlyCollection: ...
    def StoreElement(self, element: XElement, friendlyName: str) -> None: ...


class IXmlRepository:
    def GetAllElements(self) -> IReadOnlyCollection: ...
    def StoreElement(self, element: XElement, friendlyName: str) -> None: ...


class RegistryXmlRepository:
    def __init__(self, registryKey: RegistryKey, loggerFactory: ILoggerFactory): ...
    @property
    def DefaultRegistryKey() -> RegistryKey: ...
    @property
    def RegistryKey(self) -> RegistryKey: ...
    def GetAllElements(self) -> IReadOnlyCollection: ...
    def StoreElement(self, element: XElement, friendlyName: str) -> None: ...
