__all__ = ['Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Configuration','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Description','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Discovery','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols','Protocols']
from typing import Tuple, Set, Iterable, List


class WebServiceBindingAttribute(Attribute):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, name: str): ...
    @overload
    def __init__(self, name: str, ns: str): ...
    @overload
    def __init__(self, name: str, ns: str, location: str): ...
    @property
    def ConformsTo(self) -> WsiProfiles: ...
    @property
    def EmitConformanceClaims(self) -> bool: ...
    @property
    def Location(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Namespace(self) -> str: ...
    @ConformsTo.setter
    def ConformsTo(self, value: WsiProfiles) -> None: ...
    @EmitConformanceClaims.setter
    def EmitConformanceClaims(self, value: bool) -> None: ...
    @Location.setter
    def Location(self, value: str) -> None: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @Namespace.setter
    def Namespace(self, value: str) -> None: ...
