from typing import Tuple, Set, Iterable, List


class IDataflowBlock:
    def Complete(self) -> None: ...
    def Fault(self, exception: Exception) -> None: ...
    @property
    def Completion(self) -> Task: ...
