from typing import Tuple, Set, Iterable, List


class UrlResolutionTagHelper(TagHelper):
    def __init__(self, urlHelperFactory: IUrlHelperFactory, htmlEncoder: HtmlEncoder): ...
    @property
    def Order(self) -> int: ...
    @property
    def ViewContext(self) -> ViewContext: ...
    def Process(self, context: TagHelperContext, output: TagHelperOutput) -> None: ...
    @ViewContext.setter
    def ViewContext(self, value: ViewContext) -> None: ...
