from typing import Tuple, Set, Iterable, List


class DebugContext:
    def CreateInstance() -> DebugContext: ...
    @property
    def Mode(self) -> int: ...
    def ResetSourceFile(self, sourceFileName: str) -> None: ...
    @overload
    def TransformLambda(self, lambda: LambdaExpression) -> LambdaExpression: ...
    @overload
    def TransformLambda(self, lambda: LambdaExpression, lambdaInfo: DebugLambdaInfo) -> LambdaExpression: ...
