from typing import Tuple, Set, Iterable, List


class SocketTransportFactory:
    def __init__(self, options: IOptions, loggerFactory: ILoggerFactory): ...
    def BindAsync(self, endpoint: EndPoint, cancellationToken: CancellationToken) -> ValueTask: ...


class SocketTransportOptions:
    def __init__(self): ...
    @property
    def IOQueueCount(self) -> int: ...
    @property
    def MaxReadBufferSize(self) -> Nullable: ...
    @property
    def MaxWriteBufferSize(self) -> Nullable: ...
    @property
    def NoDelay(self) -> bool: ...
    @IOQueueCount.setter
    def IOQueueCount(self, value: int) -> None: ...
    @MaxReadBufferSize.setter
    def MaxReadBufferSize(self, value: Nullable) -> None: ...
    @MaxWriteBufferSize.setter
    def MaxWriteBufferSize(self, value: Nullable) -> None: ...
    @NoDelay.setter
    def NoDelay(self, value: bool) -> None: ...
