from typing import Tuple, Set, Iterable, List


class BasicProfileViolationEnumerator(Object):
    def __init__(self, list: BasicProfileViolationCollection): ...
    def Dispose(self) -> None: ...
    @property
    def Current(self) -> BasicProfileViolation: ...
    def MoveNext(self) -> bool: ...
