from typing import Tuple, Set, Iterable, List


class WorkflowInstanceProxy(Object):
    @overload
    def BeginResumeBookmark(self, bookmark: Bookmark, value: Object, callback: AsyncCallback, state: Object) -> IAsyncResult: ...
    @overload
    def BeginResumeBookmark(self, bookmark: Bookmark, value: Object, timeout: TimeSpan, callback: AsyncCallback, state: Object) -> IAsyncResult: ...
    def EndResumeBookmark(self, result: IAsyncResult) -> BookmarkResumptionResult: ...
    @property
    def Id(self) -> Guid: ...
    @property
    def WorkflowDefinition(self) -> Activity: ...
