from typing import Tuple, Set, Iterable, List


class ProviderMetadata(Object):
    @overload
    def __init__(self, providerName: str): ...
    @overload
    def __init__(self, providerName: str, session: EventLogSession, targetCultureInfo: CultureInfo): ...
    def Dispose(self) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def Events(self) -> Iterable[EventMetadata]: ...
    @property
    def HelpLink(self) -> Uri: ...
    @property
    def Id(self) -> Guid: ...
    @property
    def Keywords(self) -> List[EventKeyword]: ...
    @property
    def Levels(self) -> List[EventLevel]: ...
    @property
    def LogLinks(self) -> List[EventLogLink]: ...
    @property
    def MessageFilePath(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Opcodes(self) -> List[EventOpcode]: ...
    @property
    def ParameterFilePath(self) -> str: ...
    @property
    def ResourceFilePath(self) -> str: ...
    @property
    def Tasks(self) -> List[EventTask]: ...
