__all__ = ['Infrastructure']
from typing import Tuple, Set, Iterable, List


class CorsPolicyMetadata:
    def __init__(self, policy: CorsPolicy): ...
    @property
    def Policy(self) -> CorsPolicy: ...


class DisableCorsAttribute:
    def __init__(self): ...


class EnableCorsAttribute:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, policyName: str): ...
    @property
    def PolicyName(self) -> str: ...
    @PolicyName.setter
    def PolicyName(self, value: str) -> None: ...
