from typing import Tuple, Set, Iterable, List


class DiscoveryMessageSequenceApril2005(Object):
    def FromDiscoveryMessageSequence(discoveryMessageSequence: DiscoveryMessageSequence) -> DiscoveryMessageSequenceApril2005: ...
    @overload
    def GetSchema(self) -> XmlSchema: ...
    @overload
    def GetSchema(schemaSet: XmlSchemaSet) -> XmlQualifiedName: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def ToDiscoveryMessageSequence(self) -> DiscoveryMessageSequence: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...


class EndpointDiscoveryMetadataApril2005(Object):
    def FromEndpointDiscoveryMetadata(endpointDiscoveryMetadata: EndpointDiscoveryMetadata) -> EndpointDiscoveryMetadataApril2005: ...
    @overload
    def GetSchema(self) -> XmlSchema: ...
    @overload
    def GetSchema(schemaSet: XmlSchemaSet) -> XmlQualifiedName: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def ToEndpointDiscoveryMetadata(self) -> EndpointDiscoveryMetadata: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...


class FindCriteriaApril2005(Object):
    def FromFindCriteria(findCriteria: FindCriteria) -> FindCriteriaApril2005: ...
    @overload
    def GetSchema(self) -> XmlSchema: ...
    @overload
    def GetSchema(schemaSet: XmlSchemaSet) -> XmlQualifiedName: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def ToFindCriteria(self) -> FindCriteria: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...


class ResolveCriteriaApril2005(Object):
    def FromResolveCriteria(resolveCriteria: ResolveCriteria) -> ResolveCriteriaApril2005: ...
    @overload
    def GetSchema(self) -> XmlSchema: ...
    @overload
    def GetSchema(schemaSet: XmlSchemaSet) -> XmlQualifiedName: ...
    def ReadXml(self, reader: XmlReader) -> None: ...
    def ToResolveCriteria(self) -> ResolveCriteria: ...
    def WriteXml(self, writer: XmlWriter) -> None: ...
