from typing import Tuple, Set, Iterable, List


class ResponseCompressionProvider:
    def __init__(self, services: IServiceProvider, options: IOptions): ...
    def CheckRequestAcceptsCompression(self, context: HttpContext) -> bool: ...
    def GetCompressionProvider(self, context: HttpContext) -> ICompressionProvider: ...
    def ShouldCompressResponse(self, context: HttpContext) -> bool: ...
