__all__ = ['Cim','Cmdletization','Cmdletization','Cmdletization','Cmdletization','Cmdletization','Cmdletization','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','Commands','DesiredStateConfiguration']
from typing import Tuple, Set, Iterable, List


class PSCorePSSnapIn:
    def __init__(self): ...
    @property
    def Description(self) -> str: ...
    @property
    def DescriptionResource(self) -> str: ...
    @property
    def Formats(self) -> Set(str): ...
    @property
    def Name(self) -> str: ...
    @property
    def Types(self) -> Set(str): ...
    @property
    def Vendor(self) -> str: ...
    @property
    def VendorResource(self) -> str: ...
