__all__ = ['ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory','ActiveDirectory']
from typing import Tuple, Set, Iterable, List


class DirectoryServicesCOMException(COMException):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, message: str, inner: Exception): ...
    @property
    def ExtendedError(self) -> int: ...
    @property
    def ExtendedErrorMessage(self) -> str: ...
    def GetObjectData(self, serializationInfo: SerializationInfo, streamingContext: StreamingContext) -> None: ...
