from typing import Tuple, Set, Iterable, List


class CimCmdletAdapter:
    def __init__(self): ...
    @property
    def CimSession(self) -> Set(CimSession): ...
    @property
    def ThrottleLimit(self) -> int: ...
    def GetQueryBuilder(self) -> QueryBuilder: ...
    @CimSession.setter
    def CimSession(self, value: Set(CimSession)) -> None: ...
    @ThrottleLimit.setter
    def ThrottleLimit(self, value: int) -> None: ...


class CimJobException:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, message: str, inner: Exception): ...
    @property
    def ErrorRecord(self) -> ErrorRecord: ...
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
