from typing import Tuple, Set, Iterable, List


class SourceExpressionException(Exception):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def __init__(self, message: str, errors: CompilerErrorCollection): ...
    @property
    def Errors(self) -> Iterable[CompilerError]: ...
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...
