__all__ = ['Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Permissions','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy','Policy']
from typing import Tuple, Set, Iterable, List


class XmlSyntaxException(SystemException):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, lineNumber: int): ...
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, lineNumber: int, message: str): ...
    @overload
    def __init__(self, message: str, inner: Exception): ...
