__all__ = ['Features','Features','Features','Features','Features','Features','Features','Features','Features','Features','Features','Features','Features','Features','Features','Features']
from typing import Tuple, Set, Iterable, List


class UriEndPoint:
    def __init__(self, uri: Uri): ...
    @property
    def Uri(self) -> Uri: ...
    def ToString(self) -> str: ...
