__all__ = ['Hosting','Hosting','Hosting','Hosting','Hosting','Hosting','Hosting','Hosting','Hosting','Hosting','Hosting','Hosting','Pipeline','Pipeline','Pipeline','Pipeline','Pipeline','Pipeline','Pipeline']
from typing import Tuple, Set, Iterable, List


class AddInAttribute(Attribute):
    def __init__(self, name: str): ...
    @property
    def Description(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Publisher(self) -> str: ...
    @property
    def Version(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @Publisher.setter
    def Publisher(self, value: str) -> None: ...
    @Version.setter
    def Version(self, value: str) -> None: ...
