from typing import Tuple, Set, Iterable, List


class WebEventDescriptor:
    def __init__(self): ...
    @property
    def BrowserRendererId(self) -> int: ...
    @property
    def EventArgsType(self) -> str: ...
    @property
    def EventFieldInfo(self) -> EventFieldInfo: ...
    @property
    def EventHandlerId(self) -> UInt64: ...
    @BrowserRendererId.setter
    def BrowserRendererId(self, value: int) -> None: ...
    @EventArgsType.setter
    def EventArgsType(self, value: str) -> None: ...
    @EventFieldInfo.setter
    def EventFieldInfo(self, value: EventFieldInfo) -> None: ...
    @EventHandlerId.setter
    def EventHandlerId(self, value: UInt64) -> None: ...
