from typing import Tuple, Set, Iterable, List


class PeerPresenceInfo(Object):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, presenceStatus: PeerPresenceStatus, description: str): ...
    @property
    def DescriptiveText(self) -> str: ...
    @property
    def PresenceStatus(self) -> PeerPresenceStatus: ...
    @DescriptiveText.setter
    def DescriptiveText(self, value: str) -> None: ...
    @PresenceStatus.setter
    def PresenceStatus(self, value: PeerPresenceStatus) -> None: ...
