from typing import Tuple, Set, Iterable, List


class UITypeEditor(Object):
    def __init__(self): ...
    @overload
    def EditValue(self, provider: IServiceProvider, value: Object) -> Object: ...
    @overload
    def EditValue(self, context: ITypeDescriptorContext, provider: IServiceProvider, value: Object) -> Object: ...
    @property
    def IsDropDownResizable(self) -> bool: ...
    @overload
    def GetEditStyle(self) -> UITypeEditorEditStyle: ...
    @overload
    def GetEditStyle(self, context: ITypeDescriptorContext) -> UITypeEditorEditStyle: ...
    @overload
    def GetPaintValueSupported(self) -> bool: ...
    @overload
    def GetPaintValueSupported(self, context: ITypeDescriptorContext) -> bool: ...
    @overload
    def PaintValue(self, e: PaintValueEventArgs) -> None: ...
    @overload
    def PaintValue(self, value: Object, canvas: Graphics, rectangle: Rectangle) -> None: ...
