from typing import Tuple, Set, Iterable, List


class WebHost:
    @overload
    def CreateDefaultBuilder() -> IWebHostBuilder: ...
    @overload
    def CreateDefaultBuilder(args: Set(str)) -> IWebHostBuilder: ...
    @overload
    def CreateDefaultBuilder(args: Set(str)) -> IWebHostBuilder: ...
    @overload
    def Start(app: RequestDelegate) -> IWebHost: ...
    @overload
    def Start(routeBuilder: Action) -> IWebHost: ...
    @overload
    def Start(url: str, app: RequestDelegate) -> IWebHost: ...
    @overload
    def Start(url: str, routeBuilder: Action) -> IWebHost: ...
    @overload
    def StartWith(app: Action) -> IWebHost: ...
    @overload
    def StartWith(url: str, app: Action) -> IWebHost: ...
