from typing import Tuple, Set, Iterable, List


class SystemSounds(Object):
    @property
    def Asterisk() -> SystemSound: ...
    @property
    def Beep() -> SystemSound: ...
    @property
    def Exclamation() -> SystemSound: ...
    @property
    def Hand() -> SystemSound: ...
    @property
    def Question() -> SystemSound: ...
