from typing import Tuple, Set, Iterable, List


class ValueWebSocketReceiveResult(ValueType):
    def __init__(self, count: int, messageType: WebSocketMessageType, endOfMessage: bool): ...
    @property
    def Count(self) -> int: ...
    @property
    def EndOfMessage(self) -> bool: ...
    @property
    def MessageType(self) -> WebSocketMessageType: ...


class WebSocket(Object):
    def Abort(self) -> None: ...
    def CloseAsync(self, closeStatus: WebSocketCloseStatus, statusDescription: str, cancellationToken: CancellationToken) -> Task: ...
    def CloseOutputAsync(self, closeStatus: WebSocketCloseStatus, statusDescription: str, cancellationToken: CancellationToken) -> Task: ...
    def CreateClientBuffer(receiveBufferSize: int, sendBufferSize: int) -> ArraySegment: ...
    def CreateClientWebSocket(innerStream: Stream, subProtocol: str, receiveBufferSize: int, sendBufferSize: int, keepAliveInterval: TimeSpan, useZeroMaskingKey: bool, internalBuffer: ArraySegment) -> WebSocket: ...
    @overload
    def CreateFromStream(stream: Stream, options: WebSocketCreationOptions) -> WebSocket: ...
    @overload
    def CreateFromStream(stream: Stream, isServer: bool, subProtocol: str, keepAliveInterval: TimeSpan) -> WebSocket: ...
    def CreateServerBuffer(receiveBufferSize: int) -> ArraySegment: ...
    def Dispose(self) -> None: ...
    @property
    def CloseStatus(self) -> Nullable: ...
    @property
    def CloseStatusDescription(self) -> str: ...
    @property
    def DefaultKeepAliveInterval() -> TimeSpan: ...
    @property
    def State(self) -> WebSocketState: ...
    @property
    def SubProtocol(self) -> str: ...
    @overload
    def ReceiveAsync(self, buffer: Memory, cancellationToken: CancellationToken) -> ValueTask: ...
    @overload
    def ReceiveAsync(self, buffer: ArraySegment, cancellationToken: CancellationToken) -> Task: ...
    @overload
    def SendAsync(self, buffer: ArraySegment, messageType: WebSocketMessageType, endOfMessage: bool, cancellationToken: CancellationToken) -> Task: ...
    @overload
    def SendAsync(self, buffer: ReadOnlyMemory, messageType: WebSocketMessageType, endOfMessage: bool, cancellationToken: CancellationToken) -> ValueTask: ...
    @overload
    def SendAsync(self, buffer: ReadOnlyMemory, messageType: WebSocketMessageType, messageFlags: WebSocketMessageFlags, cancellationToken: CancellationToken) -> ValueTask: ...


class WebSocketCloseStatus:
    NormalClosure = 1000
    EndpointUnavailable = 1001
    ProtocolError = 1002
    InvalidMessageType = 1003
    Empty = 1005
    InvalidPayloadData = 1007
    PolicyViolation = 1008
    MessageTooBig = 1009
    MandatoryExtension = 1010
    InternalServerError = 1011


class WebSocketContext(Object):
    @property
    def CookieCollection(self) -> CookieCollection: ...
    @property
    def Headers(self) -> NameValueCollection: ...
    @property
    def IsAuthenticated(self) -> bool: ...
    @property
    def IsLocal(self) -> bool: ...
    @property
    def IsSecureConnection(self) -> bool: ...
    @property
    def Origin(self) -> str: ...
    @property
    def RequestUri(self) -> Uri: ...
    @property
    def SecWebSocketKey(self) -> str: ...
    @property
    def SecWebSocketProtocols(self) -> Iterable[str]: ...
    @property
    def SecWebSocketVersion(self) -> str: ...
    @property
    def User(self) -> IPrincipal: ...
    @property
    def WebSocket(self) -> WebSocket: ...


class WebSocketCreationOptions(Object):
    def __init__(self): ...
    @property
    def DangerousDeflateOptions(self) -> WebSocketDeflateOptions: ...
    @property
    def IsServer(self) -> bool: ...
    @property
    def KeepAliveInterval(self) -> TimeSpan: ...
    @property
    def SubProtocol(self) -> str: ...
    @DangerousDeflateOptions.setter
    def DangerousDeflateOptions(self, value: WebSocketDeflateOptions) -> None: ...
    @IsServer.setter
    def IsServer(self, value: bool) -> None: ...
    @KeepAliveInterval.setter
    def KeepAliveInterval(self, value: TimeSpan) -> None: ...
    @SubProtocol.setter
    def SubProtocol(self, value: str) -> None: ...


class WebSocketDeflateOptions(Object):
    def __init__(self): ...
    @property
    def ClientContextTakeover(self) -> bool: ...
    @property
    def ClientMaxWindowBits(self) -> int: ...
    @property
    def ServerContextTakeover(self) -> bool: ...
    @property
    def ServerMaxWindowBits(self) -> int: ...
    @ClientContextTakeover.setter
    def ClientContextTakeover(self, value: bool) -> None: ...
    @ClientMaxWindowBits.setter
    def ClientMaxWindowBits(self, value: int) -> None: ...
    @ServerContextTakeover.setter
    def ServerContextTakeover(self, value: bool) -> None: ...
    @ServerMaxWindowBits.setter
    def ServerMaxWindowBits(self, value: int) -> None: ...


class WebSocketError:
    Success = 0
    InvalidMessageType = 1
    Faulted = 2
    NativeError = 3
    NotAWebSocket = 4
    UnsupportedVersion = 5
    UnsupportedProtocol = 6
    HeaderError = 7
    ConnectionClosedPrematurely = 8
    InvalidState = 9


class WebSocketException(Win32Exception):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, error: WebSocketError): ...
    @overload
    def __init__(self, nativeError: int): ...
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, error: WebSocketError, message: str): ...
    @overload
    def __init__(self, error: WebSocketError, innerException: Exception): ...
    @overload
    def __init__(self, nativeError: int, message: str): ...
    @overload
    def __init__(self, nativeError: int, innerException: Exception): ...
    @overload
    def __init__(self, error: WebSocketError, nativeError: int): ...
    @overload
    def __init__(self, message: str, innerException: Exception): ...
    @overload
    def __init__(self, error: WebSocketError, message: str, innerException: Exception): ...
    @overload
    def __init__(self, error: WebSocketError, nativeError: int, message: str): ...
    @overload
    def __init__(self, error: WebSocketError, nativeError: int, innerException: Exception): ...
    @overload
    def __init__(self, error: WebSocketError, nativeError: int, message: str, innerException: Exception): ...
    @property
    def ErrorCode(self) -> int: ...
    @property
    def WebSocketErrorCode(self) -> WebSocketError: ...
    def GetObjectData(self, info: SerializationInfo, context: StreamingContext) -> None: ...


class WebSocketMessageFlags:
    #None = 0
    EndOfMessage = 1
    DisableCompression = 2


class WebSocketMessageType:
    Text = 0
    Binary = 1
    Close = 2


class WebSocketReceiveResult(Object):
    @overload
    def __init__(self, count: int, messageType: WebSocketMessageType, endOfMessage: bool): ...
    @overload
    def __init__(self, count: int, messageType: WebSocketMessageType, endOfMessage: bool, closeStatus: Nullable, closeStatusDescription: str): ...
    @property
    def CloseStatus(self) -> Nullable: ...
    @property
    def CloseStatusDescription(self) -> str: ...
    @property
    def Count(self) -> int: ...
    @property
    def EndOfMessage(self) -> bool: ...
    @property
    def MessageType(self) -> WebSocketMessageType: ...


class WebSocketState:
    #None = 0
    Connecting = 1
    Open = 2
    CloseSent = 3
    CloseReceived = 4
    Closed = 5
    Aborted = 6
