from typing import Tuple, Set, Iterable, List


class AppvPublishingServer:
    def __init__(self, server: IPublishingServer): ...
    def EnumeratePublishingServers() -> Iterable[AppvPublishingServer]: ...
    @property
    def GlobalRefreshEnabled(self) -> bool: ...
    @property
    def GlobalRefreshInterval(self) -> UInt32: ...
    @property
    def GlobalRefreshIntervalUnit(self) -> str: ...
    @property
    def GlobalRefreshOnLogon(self) -> bool: ...
    @property
    def ID(self) -> UInt32: ...
    @property
    def SetByGroupPolicy(self) -> bool: ...
    @property
    def Url(self) -> str: ...
    @property
    def UserRefreshEnabled(self) -> bool: ...
    @property
    def UserRefreshInterval(self) -> UInt32: ...
    @property
    def UserRefreshIntervalUnit(self) -> str: ...
    @property
    def UserRefreshOnLogon(self) -> bool: ...
    def GetInstance(serverId: int) -> AppvPublishingServer: ...
