from typing import Tuple, Set, Iterable, List


class DevicesGPOSetting:
    def __init__(self): ...
    def GetHashKey(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...


class DevicesGPOSettings(PolicyMakerElement):
    def __init__(self): ...
    @property
    def Devices(self) -> Collection: ...
    @Devices.setter
    def Devices(self, value: Collection) -> None: ...


class DevicesRsopSetting(PolicyMakerRsopSetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, managementObject: ManagementObject): ...
    def GetHashKey(self) -> str: ...
    def GetItemSubInstanceAttributeName(self) -> str: ...
    def GetKeyComponents(self) -> Set(str): ...


class DevicesSettings(PolicyMakerSettings):
    def __init__(self): ...
    @property
    def DevicesGPOSettings(self) -> DevicesGPOSettings: ...
    @property
    def DevicesRsopSettings(self) -> Collection: ...
    def GetGPOSettings(self) -> ICollection: ...
    def GetRsopSettings(self) -> ICollection: ...
    def Initialize(self, context: ReportingContext) -> None: ...
    @DevicesGPOSettings.setter
    def DevicesGPOSettings(self, value: DevicesGPOSettings) -> None: ...
    @DevicesRsopSettings.setter
    def DevicesRsopSettings(self, value: Collection) -> None: ...
