from typing import Tuple, Set, Iterable, List


class IniStreamConfigurationSource(StreamConfigurationSource):
    def __init__(self): ...
    def Build(self, builder: IConfigurationBuilder) -> IConfigurationProvider: ...
