from typing import Tuple, Set, Iterable, List


class WorkflowMarkupSerializer(Object):
    def __init__(self): ...
    @overload
    def Deserialize(self, reader: XmlReader) -> Object: ...
    @overload
    def Deserialize(self, serializationManager: IDesignerSerializationManager, reader: XmlReader) -> Object: ...
    @overload
    def Serialize(self, writer: XmlWriter, obj: Object) -> None: ...
    @overload
    def Serialize(self, serializationManager: IDesignerSerializationManager, writer: XmlWriter, obj: Object) -> None: ...
