from typing import Tuple, Set, Iterable, List


class PSRunOrder:
    PSNotConfigured = 0
    RunPSFirst = 1
    RunPSSecond = 2


class ScriptSetting(PolicySetting):
    def __init__(self): ...
    @property
    def Command(self) -> str: ...
    @property
    def ExecutionTime(self) -> DateTime: ...
    @property
    def ExecutionTimeSpecified(self) -> bool: ...
    @property
    def Order(self) -> UInt32: ...
    @property
    def Parameters(self) -> str: ...
    @property
    def RunOrder(self) -> PSRunOrder: ...
    @property
    def Type(self) -> ScriptType: ...
    @Command.setter
    def Command(self, value: str) -> None: ...
    @ExecutionTime.setter
    def ExecutionTime(self, value: DateTime) -> None: ...
    @ExecutionTimeSpecified.setter
    def ExecutionTimeSpecified(self, value: bool) -> None: ...
    @Order.setter
    def Order(self, value: UInt32) -> None: ...
    @Parameters.setter
    def Parameters(self, value: str) -> None: ...
    @RunOrder.setter
    def RunOrder(self, value: PSRunOrder) -> None: ...
    @Type.setter
    def Type(self, value: ScriptType) -> None: ...


class ScriptSettings(GPOExtension):
    def __init__(self): ...
    @property
    def Script(self) -> ArrayList: ...
    def Initialize(self, context: ReportingContext) -> None: ...
    @Script.setter
    def Script(self, value: ArrayList) -> None: ...


class ScriptType:
    #None = 0
    Logon = 1
    Logoff = 2
    Startup = 3
    Shutdown = 4
