from typing import Tuple, Set, Iterable, List


class ScriptSettings(GPOExtension):
    def __init__(self): ...
    @property
    def Script(self) -> ArrayList: ...
    def Initialize(self, context: ReportingContext) -> None: ...
    @Script.setter
    def Script(self, value: ArrayList) -> None: ...
