from typing import Tuple, Set, Iterable, List


class WorkflowServiceHostFactory(ServiceHostFactoryBase):
    def __init__(self): ...
    def CreateServiceHost(self, constructorString: str, baseAddresses: Set(Uri)) -> ServiceHostBase: ...
