__all__ = ['Configuration','Configuration','Configuration','Configuration','Configuration','Providers']
from typing import Tuple, Set, Iterable, List


class TokenCategorizer:
    @property
    def CurrentPosition(self) -> SourceLocation: ...
    @property
    def CurrentState(self) -> Object: ...
    @property
    def ErrorSink(self) -> ErrorSink: ...
    @property
    def IsRestartable(self) -> bool: ...
    def Initialize(self, state: Object, scriptSource: ScriptSource, initialLocation: SourceLocation) -> None: ...
    def InitializeLifetimeService(self) -> Object: ...
    def ReadToken(self) -> TokenInfo: ...
    def ReadTokens(self, characterCount: int) -> Iterable[TokenInfo]: ...
    @ErrorSink.setter
    def ErrorSink(self, value: ErrorSink) -> None: ...
    def SkipToken(self) -> bool: ...
    def SkipTokens(self, characterCount: int) -> bool: ...
