from typing import Tuple, Set, Iterable, List


class Plugin(PolicyElement):
    def __init__(self): ...
    @property
    def ExecutionCategories(self) -> List: ...
    @property
    def Id(self) -> Id: ...
    @property
    def Name(self) -> str: ...
    @Id.setter
    def Id(self, value: Id) -> None: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
