__all__ = ['Schema','Schema','Schema','Schema','Schema','Schema','Schema','Schema']
from typing import Tuple, Set, Iterable, List


class ValidationContext(Object):
    @overload
    def __init__(self, instance: Object): ...
    @overload
    def __init__(self, instance: Object, items: IDictionary): ...
    @overload
    def __init__(self, instance: Object, serviceProvider: IServiceProvider, items: IDictionary): ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def Items(self) -> IDictionary: ...
    @property
    def MemberName(self) -> str: ...
    @property
    def ObjectInstance(self) -> Object: ...
    @property
    def ObjectType(self) -> Type: ...
    @property
    def ServiceContainer(self) -> IServiceContainer: ...
    def GetService(self, serviceType: Type) -> Object: ...
    def InitializeServiceProvider(self, serviceProvider: Func) -> None: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...
    @MemberName.setter
    def MemberName(self, value: str) -> None: ...
