__all__ = ['Mail','Mail','Mail','NetworkInformation','NetworkInformation','NetworkInformation','PeerToPeer','PeerToPeer','PeerToPeer']
from typing import Tuple, Set, Iterable, List


class WebPermissionAttribute(CodeAccessSecurityAttribute):
    def __init__(self, action: SecurityAction): ...
    def CreatePermission(self) -> IPermission: ...
    @property
    def Accept(self) -> str: ...
    @property
    def AcceptPattern(self) -> str: ...
    @property
    def Connect(self) -> str: ...
    @property
    def ConnectPattern(self) -> str: ...
    @Accept.setter
    def Accept(self, value: str) -> None: ...
    @AcceptPattern.setter
    def AcceptPattern(self, value: str) -> None: ...
    @Connect.setter
    def Connect(self, value: str) -> None: ...
    @ConnectPattern.setter
    def ConnectPattern(self, value: str) -> None: ...
