from typing import Tuple, Set, Iterable, List


class SrgsToken(SrgsElement):
    def __init__(self, text: str): ...
    @property
    def Display(self) -> str: ...
    @property
    def Pronunciation(self) -> str: ...
    @property
    def Text(self) -> str: ...
    @Display.setter
    def Display(self, value: str) -> None: ...
    @Pronunciation.setter
    def Pronunciation(self, value: str) -> None: ...
    @Text.setter
    def Text(self, value: str) -> None: ...
