from typing import Tuple, Set, Iterable, List


class RoleProvider(ProviderBase):
    def AddUsersToRoles(self, usernames: Set(str), roleNames: Set(str)) -> None: ...
    def CreateRole(self, roleName: str) -> None: ...
    def DeleteRole(self, roleName: str, throwOnPopulatedRole: bool) -> bool: ...
    def FindUsersInRole(self, roleName: str, usernameToMatch: str) -> Set(str): ...
    @property
    def ApplicationName(self) -> str: ...
    def GetAllRoles(self) -> Set(str): ...
    def GetRolesForUser(self, username: str) -> Set(str): ...
    def GetUsersInRole(self, roleName: str) -> Set(str): ...
    def IsUserInRole(self, username: str, roleName: str) -> bool: ...
    def RemoveUsersFromRoles(self, usernames: Set(str), roleNames: Set(str)) -> None: ...
    def RoleExists(self, roleName: str) -> bool: ...
    @ApplicationName.setter
    def ApplicationName(self, value: str) -> None: ...
