from typing import Tuple, Set, Iterable, List


class CLSID_StartLayoutCmdlet:
    def __init__(self): ...


class ExportEdgeAssetsCommand:
    def __init__(self): ...
    @property
    def LiteralPath(self) -> str: ...
    @property
    def Path(self) -> str: ...
    @LiteralPath.setter
    def LiteralPath(self, value: str) -> None: ...
    @Path.setter
    def Path(self, value: str) -> None: ...


class ExportStartLayoutCommand:
    def __init__(self): ...
    @property
    def LiteralPath(self) -> str: ...
    @property
    def Path(self) -> str: ...
    @property
    def UseDesktopApplicationID(self) -> SwitchParameter: ...
    @LiteralPath.setter
    def LiteralPath(self, value: str) -> None: ...
    @Path.setter
    def Path(self, value: str) -> None: ...
    @UseDesktopApplicationID.setter
    def UseDesktopApplicationID(self, value: SwitchParameter) -> None: ...


class ImportStartLayoutCommand:
    def __init__(self): ...
    @property
    def LayoutLiteralPath(self) -> str: ...
    @property
    def LayoutPath(self) -> str: ...
    @property
    def MountLiteralPath(self) -> str: ...
    @property
    def MountPath(self) -> str: ...
    @LayoutLiteralPath.setter
    def LayoutLiteralPath(self, value: str) -> None: ...
    @LayoutPath.setter
    def LayoutPath(self, value: str) -> None: ...
    @MountLiteralPath.setter
    def MountLiteralPath(self, value: str) -> None: ...
    @MountPath.setter
    def MountPath(self, value: str) -> None: ...


class IStartLayoutCmdlet:
    def ExportEdgeAssets(self, pszFilePath: str) -> None: ...
    def ExportStartLayout(self, pszFilePath: str) -> None: ...
    def ExportStartLayoutWithDesktopApplicationIDs(self, pszFilePath: str) -> None: ...
    def ValidateLayoutFile(self, pszFilePath: str) -> None: ...
