from typing import Tuple, Set, Iterable, List


class PageHandlerSelectedContext(FilterContext):
    def __init__(self, pageContext: PageContext, filters: List[IFilterMetadata], handlerInstance: Object): ...
    @property
    def ActionDescriptor(self) -> CompiledPageActionDescriptor: ...
    @property
    def HandlerInstance(self) -> Object: ...
    @property
    def HandlerMethod(self) -> HandlerMethodDescriptor: ...
    @HandlerMethod.setter
    def HandlerMethod(self, value: HandlerMethodDescriptor) -> None: ...
