from typing import Tuple, Set, Iterable, List


class PSStreamObject(Object):
    def __init__(self, objectType: PSStreamObjectType, value: Object): ...
    @property
    def ObjectType(self) -> PSStreamObjectType: ...
    @ObjectType.setter
    def ObjectType(self, value: PSStreamObjectType) -> None: ...
    def WriteStreamObject(self, cmdlet: Cmdlet, overrideInquire: bool) -> None: ...
