from typing import Tuple, Set, Iterable, List


class ServiceControllerPermissionAccess:
    #None = 0
    Browse = 2
    Control = 6


class ServiceControllerPermissionEntry(Object):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, permissionAccess: ServiceControllerPermissionAccess, machineName: str, serviceName: str): ...
    @property
    def MachineName(self) -> str: ...
    @property
    def PermissionAccess(self) -> ServiceControllerPermissionAccess: ...
    @property
    def ServiceName(self) -> str: ...


class ServiceControllerPermissionEntryCollection(CollectionBase):
    def Add(self, value: ServiceControllerPermissionEntry) -> int: ...
    @overload
    def AddRange(self, value: Set(ServiceControllerPermissionEntry)) -> None: ...
    @overload
    def AddRange(self, value: ServiceControllerPermissionEntryCollection) -> None: ...
    def Contains(self, value: ServiceControllerPermissionEntry) -> bool: ...
    def CopyTo(self, array: Set(ServiceControllerPermissionEntry), index: int) -> None: ...
    @property
    def Item(self, index: int) -> ServiceControllerPermissionEntry: ...
    def IndexOf(self, value: ServiceControllerPermissionEntry) -> int: ...
    def Insert(self, index: int, value: ServiceControllerPermissionEntry) -> None: ...
    def Remove(self, value: ServiceControllerPermissionEntry) -> None: ...
    @Item.setter
    def Item(self, index: int, value: ServiceControllerPermissionEntry) -> None: ...
