from typing import Tuple, Set, Iterable, List


class TrustRelationshipInformationCollection(ReadOnlyCollectionBase):
    def Contains(self, information: TrustRelationshipInformation) -> bool: ...
    def CopyTo(self, array: Set(TrustRelationshipInformation), index: int) -> None: ...
    @property
    def Item(self, index: int) -> TrustRelationshipInformation: ...
    def IndexOf(self, information: TrustRelationshipInformation) -> int: ...
