from typing import Tuple, Set, Iterable, List


class FolderSettingLocation:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, groupSid: str, path: str, server: str): ...
    @property
    def DestinationPath(self) -> str: ...
    @property
    def SecurityGroup(self) -> Trustee: ...
    @DestinationPath.setter
    def DestinationPath(self, value: str) -> None: ...
    @SecurityGroup.setter
    def SecurityGroup(self, value: Trustee) -> None: ...
