from typing import Tuple, Set, Iterable, List


class WebSocketOptions:
    def __init__(self): ...
    @property
    def AllowedOrigins(self) -> List[str]: ...
    @property
    def KeepAliveInterval(self) -> TimeSpan: ...
    @property
    def ReceiveBufferSize(self) -> int: ...
    @KeepAliveInterval.setter
    def KeepAliveInterval(self, value: TimeSpan) -> None: ...
    @ReceiveBufferSize.setter
    def ReceiveBufferSize(self, value: int) -> None: ...
