from typing import Tuple, Set, Iterable, List


class SocketTransportOptions:
    def __init__(self): ...
    @property
    def Backlog(self) -> int: ...
    @property
    def IOQueueCount(self) -> int: ...
    @property
    def MaxReadBufferSize(self) -> Nullable: ...
    @property
    def MaxWriteBufferSize(self) -> Nullable: ...
    @property
    def NoDelay(self) -> bool: ...
    @property
    def UnsafePreferInlineScheduling(self) -> bool: ...
    @property
    def WaitForDataBeforeAllocatingBuffer(self) -> bool: ...
    @Backlog.setter
    def Backlog(self, value: int) -> None: ...
    @IOQueueCount.setter
    def IOQueueCount(self, value: int) -> None: ...
    @MaxReadBufferSize.setter
    def MaxReadBufferSize(self, value: Nullable) -> None: ...
    @MaxWriteBufferSize.setter
    def MaxWriteBufferSize(self, value: Nullable) -> None: ...
    @NoDelay.setter
    def NoDelay(self, value: bool) -> None: ...
    @UnsafePreferInlineScheduling.setter
    def UnsafePreferInlineScheduling(self, value: bool) -> None: ...
    @WaitForDataBeforeAllocatingBuffer.setter
    def WaitForDataBeforeAllocatingBuffer(self, value: bool) -> None: ...
