from typing import Tuple, Set, Iterable, List


class DriveMapGPOSetting:
    def __init__(self): ...
    def GetHashKey(self) -> str: ...


class DriveMapGPOSettings(PolicyMakerElement):
    def __init__(self): ...
    @property
    def DriveMappings(self) -> List: ...
    @DriveMappings.setter
    def DriveMappings(self, value: List) -> None: ...


class DriveMapRsopSetting(PolicyMakerRsopSetting):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, managementObject: ManagementObject): ...
    def GetHashKey(self) -> str: ...
    def GetItemSubInstanceAttributeName(self) -> str: ...


class DriveMapSettings(PolicyMakerSettings):
    def __init__(self): ...
    @property
    def DriveMapGPOSettings(self) -> DriveMapGPOSettings: ...
    @property
    def DriveMapRsopSettings(self) -> List: ...
    def GetGPOSettings(self) -> ICollection: ...
    def GetRsopSettings(self) -> ICollection: ...
    def Initialize(self, context: ReportingContext) -> None: ...
    @DriveMapGPOSettings.setter
    def DriveMapGPOSettings(self, value: DriveMapGPOSettings) -> None: ...
    @DriveMapRsopSettings.setter
    def DriveMapRsopSettings(self, value: List) -> None: ...
