__all__ = ['Core','Core','Core','Core','Core','Core','Core','Core','Https','Https','Https']
from typing import Tuple, Set, Iterable, List


class KestrelConfigurationLoader:
    @overload
    def AnyIPEndpoint(self, port: int) -> KestrelConfigurationLoader: ...
    @overload
    def AnyIPEndpoint(self, port: int, configure: Action) -> KestrelConfigurationLoader: ...
    @overload
    def Endpoint(self, endPoint: IPEndPoint) -> KestrelConfigurationLoader: ...
    @overload
    def Endpoint(self, name: str, configureOptions: Action) -> KestrelConfigurationLoader: ...
    @overload
    def Endpoint(self, address: IPAddress, port: int) -> KestrelConfigurationLoader: ...
    @overload
    def Endpoint(self, endPoint: IPEndPoint, configure: Action) -> KestrelConfigurationLoader: ...
    @overload
    def Endpoint(self, address: IPAddress, port: int, configure: Action) -> KestrelConfigurationLoader: ...
    @property
    def Configuration(self) -> IConfiguration: ...
    @property
    def Options(self) -> KestrelServerOptions: ...
    @overload
    def HandleEndpoint(self, handle: UInt64) -> KestrelConfigurationLoader: ...
    @overload
    def HandleEndpoint(self, handle: UInt64, configure: Action) -> KestrelConfigurationLoader: ...
    def Load(self) -> None: ...
    @overload
    def LocalhostEndpoint(self, port: int) -> KestrelConfigurationLoader: ...
    @overload
    def LocalhostEndpoint(self, port: int, configure: Action) -> KestrelConfigurationLoader: ...
    @overload
    def UnixSocketEndpoint(self, socketPath: str) -> KestrelConfigurationLoader: ...
    @overload
    def UnixSocketEndpoint(self, socketPath: str, configure: Action) -> KestrelConfigurationLoader: ...
