__all__ = ['Html','Html','RsopEnhancements','RsopEnhancements','RsopEnhancements','RsopEnhancements','RsopEnhancements','RsopEnhancements','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Security','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities','Utilities']
from typing import Tuple, Set, Iterable, List


class TemplateUserOrComputerConfig:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, extensions: Set(str), context: TemplateContext, sysvolVersion: UInt16, enabled: bool): ...
    @property
    def ExtensionData(self) -> ArrayList: ...
    @property
    def VersionSysvol(self) -> UInt16: ...
    @ExtensionData.setter
    def ExtensionData(self, value: ArrayList) -> None: ...
    @VersionSysvol.setter
    def VersionSysvol(self, value: UInt16) -> None: ...
