from typing import Tuple, Set, Iterable, List


class TypeElementCollection(ConfigurationElementCollection):
    def __init__(self): ...
    def Add(self, element: TypeElement) -> None: ...
    def Clear(self) -> None: ...
    @property
    def CollectionType(self) -> ConfigurationElementCollectionType: ...
    @property
    def Item(self, index: int) -> TypeElement: ...
    def IndexOf(self, element: TypeElement) -> int: ...
    def Remove(self, element: TypeElement) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    @Item.setter
    def Item(self, index: int, value: TypeElement) -> None: ...
