__all__ = ['Implementation']
from typing import Tuple, Set, Iterable, List


class DragDropInfo:
    def __init__(self, location: Point, keyStates: DragDropKeyStates, data: IDataObject, isInternal: bool, source: Object, allowedEffects: DragDropEffects, bufferPosition: VirtualSnapshotPoint): ...
    def Equals(self, obj: Object) -> bool: ...
    @property
    def AllowedEffects(self) -> DragDropEffects: ...
    @property
    def Data(self) -> IDataObject: ...
    @property
    def IsInternal(self) -> bool: ...
    @property
    def KeyStates(self) -> DragDropKeyStates: ...
    @property
    def Location(self) -> Point: ...
    @property
    def Source(self) -> Object: ...
    @property
    def VirtualBufferPosition(self) -> VirtualSnapshotPoint: ...
    def GetHashCode(self) -> int: ...
    def op_Equality(first: DragDropInfo, second: DragDropInfo) -> bool: ...
    def op_Inequality(first: DragDropInfo, second: DragDropInfo) -> bool: ...


class DragDropPointerEffects:
    #None = 0
    Copy = 1
    Link = 2
    Move = 4
    Scroll = 8
    Track = 16
    All = 31


class DropFormatAttribute:
    def __init__(self, dropFormat: str): ...
    @property
    def DropFormats(self) -> str: ...


class DropHandlerBase:
    def HandleDataDropped(self, dragDropInfo: DragDropInfo) -> DragDropPointerEffects: ...
    def HandleDragCanceled(self) -> None: ...
    def HandleDraggingOver(self, dragDropInfo: DragDropInfo) -> DragDropPointerEffects: ...
    def HandleDragStarted(self, dragDropInfo: DragDropInfo) -> DragDropPointerEffects: ...
    def IsDropEnabled(self, dragDropInfo: DragDropInfo) -> bool: ...


class IDropHandler:
    def HandleDataDropped(self, dragDropInfo: DragDropInfo) -> DragDropPointerEffects: ...
    def HandleDragCanceled(self) -> None: ...
    def HandleDraggingOver(self, dragDropInfo: DragDropInfo) -> DragDropPointerEffects: ...
    def HandleDragStarted(self, dragDropInfo: DragDropInfo) -> DragDropPointerEffects: ...
    def IsDropEnabled(self, dragDropInfo: DragDropInfo) -> bool: ...


class IDropHandlerProvider:
    def GetAssociatedDropHandler(self, wpfTextView: IWpfTextView) -> IDropHandler: ...
