from typing import Tuple, Set, Iterable, List


class DirectoryInfoBase(FileSystemInfoBase):
    def EnumerateFileSystemInfos(self) -> Iterable[FileSystemInfoBase]: ...
    def GetDirectory(self, path: str) -> DirectoryInfoBase: ...
    def GetFile(self, path: str) -> FileInfoBase: ...


class DirectoryInfoWrapper(DirectoryInfoBase):
    def __init__(self, directoryInfo: DirectoryInfo): ...
    def EnumerateFileSystemInfos(self) -> Iterable[FileSystemInfoBase]: ...
    @property
    def FullName(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def ParentDirectory(self) -> DirectoryInfoBase: ...
    def GetDirectory(self, name: str) -> DirectoryInfoBase: ...
    def GetFile(self, name: str) -> FileInfoBase: ...


class FileInfoBase(FileSystemInfoBase):
    pass


class FileInfoWrapper(FileInfoBase):
    def __init__(self, fileInfo: FileInfo): ...
    @property
    def FullName(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def ParentDirectory(self) -> DirectoryInfoBase: ...


class FileSystemInfoBase:
    @property
    def FullName(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def ParentDirectory(self) -> DirectoryInfoBase: ...
