__all__ = ['Internal','Internal','Internal','Internal','Internal','Internal','Internal']
from typing import Tuple, Set, Iterable, List


class XmlKeyManager:
    @overload
    def __init__(self, keyManagementOptions: IOptions, activator: IActivator): ...
    @overload
    def __init__(self, keyManagementOptions: IOptions, activator: IActivator, loggerFactory: ILoggerFactory): ...
    def CreateNewKey(self, activationDate: DateTimeOffset, expirationDate: DateTimeOffset) -> IKey: ...
    def GetAllKeys(self) -> IReadOnlyCollection: ...
    def GetCacheExpirationToken(self) -> CancellationToken: ...
    def RevokeAllKeys(self, revocationDate: DateTimeOffset, reason: str) -> None: ...
    def RevokeKey(self, keyId: Guid, reason: str) -> None: ...
