from typing import Tuple, Set, Iterable, List


class Extensions(Object):
    @overload
    def CreateNavigator(node: XNode) -> XPathNavigator: ...
    @overload
    def CreateNavigator(node: XNode, nameTable: XmlNameTable) -> XPathNavigator: ...
    @overload
    def XPathEvaluate(node: XNode, expression: str) -> Object: ...
    @overload
    def XPathEvaluate(node: XNode, expression: str, resolver: IXmlNamespaceResolver) -> Object: ...
    @overload
    def XPathSelectElement(node: XNode, expression: str) -> XElement: ...
    @overload
    def XPathSelectElement(node: XNode, expression: str, resolver: IXmlNamespaceResolver) -> XElement: ...
    @overload
    def XPathSelectElements(node: XNode, expression: str) -> Iterable[XElement]: ...
    @overload
    def XPathSelectElements(node: XNode, expression: str, resolver: IXmlNamespaceResolver) -> Iterable[XElement]: ...


class XDocumentExtensions(Object):
    def ToXPathNavigable(node: XNode) -> IXPathNavigable: ...
